/* Cours : Chimie — Ch.1 : Description et évolution d'un système vers un état final lors d'une transformation chimique */
window.OSCILLO_COURSES = window.OSCILLO_COURSES || [];
window.OSCILLO_COURSES.push({
  subject: "chimie",
  id: "c1",
  name: "Description et évolution d'un système chimique",
  cards: [
    {id:"def-systeme-transformation", type:"def", q:"Définir système chimique, état initial, état final, transformation chimique", a:"Système : ensemble d'espèces chimiques étudié. État initial/final : composition avant/après la transformation. Transformation chimique : passage d'un état à un autre via une ou plusieurs réactions."},
    {id:"def-avancement", type:"def", q:"Définir l'avancement de réaction $\\xi$", a:"Variable (en mol) décrivant la progression de la réaction : pour chaque espèce $i$ de nombre stœchiométrique algébrique $\\nu_i$, $n_i(t) = n_i(0) + \\nu_i\\xi(t)$."},
    {id:"methode-tableau-avancement", type:"méthode", q:"Méthode : construire un tableau d'avancement", a:"Lignes = état initial, en cours ($\\xi$), état final ($\\xi_{max}$ ou $\\xi_{eq}$). Colonnes = chaque espèce avec $n_i(0)+\\nu_i\\xi$. Permet de trouver le réactif limitant (premier $n_i$ à s'annuler) et l'avancement maximal."},
    {id:"def-reactif-limitant-taux-avancement", type:"def", q:"Définir réactif limitant et taux d'avancement final", a:"Réactif limitant : réactif totalement consommé en premier, fixe $\\xi_{max}$. Taux d'avancement final : $\\tau = \\xi_{eq}/\\xi_{max}$ (proportion de la transformation réalisée à l'équilibre)."},
    {id:"def-activite-especes", type:"def", q:"Définir l'activité d'une espèce chimique (convention)", a:"Gaz : $a_i = P_i/P^\\circ$ ($P^\\circ=1$ bar). Soluté dilué : $a_i = C_i/C^\\circ$ ($C^\\circ=1$ mol/L). Solvant et solide/liquide seuls dans leur phase : $a_i=1$."},
    {id:"def-quotient-reaction", type:"def", q:"Définir le quotient de réaction $Q_r$", a:"Pour $\\sum \\nu_i A_i = 0$ : $$Q_r = \\prod_i a_i^{\\nu_i}$$ (produit des activités élevées à la puissance de leur nombre stœchiométrique algébrique)."},
    {id:"def-constante-equilibre", type:"def", q:"Définir la constante d'équilibre standard $K^\\circ$", a:"Valeur de $Q_r$ à l'équilibre thermodynamique, ne dépend que de la température : $K^\\circ(T) = Q_{r,eq}$."},
    {id:"prop-condition-evolution", type:"propriété", q:"Condition d'évolution spontanée d'un système (critère $Q_r$ vs $K^\\circ$)", a:"Si $Q_r < K^\\circ$ : évolution dans le sens direct (sens 1). Si $Q_r > K^\\circ$ : évolution dans le sens indirect (sens 2). Si $Q_r = K^\\circ$ : système à l'équilibre."},
    {id:"def-etat-equilibre-rupture", type:"def", q:"Définir état d'équilibre chimique et rupture d'équilibre", a:"Équilibre : $Q_r=K^\\circ$, composition macroscopique constante dans le temps. Rupture d'équilibre : perturbation externe (T, P, concentration) qui rend $Q_r \\ne K^\\circ$, provoquant une nouvelle évolution."},
    {id:"prop-loi-le-chatelier", type:"propriété", q:"Loi de modération (Le Chatelier) : effet d'une perturbation", a:"Un système à l'équilibre soumis à une perturbation évolue dans le sens qui s'oppose (modère) à cette perturbation : ex. augmentation de T favorise le sens endothermique, augmentation de P favorise le sens qui diminue la quantité de matière gazeuse."},
    {id:"prop-effet-dilution", type:"propriété", q:"Effet d'une dilution sur un équilibre (loi de modération)", a:"Une dilution déplace l'équilibre dans le sens qui produit le plus de moles de solutés (augmente la quantité de matière dissoute) pour s'opposer à la baisse de concentration."},
    {id:"prop-facteurs-cinetiques", type:"propriété", q:"Facteurs cinétiques (rappel, influencent la vitesse pas l'équilibre)", a:"Température, concentration des réactifs, catalyseur : modifient la vitesse à laquelle l'équilibre est atteint, mais PAS la valeur de $K^\\circ$ ni la composition finale à l'équilibre (sauf T qui modifie $K^\\circ$)."},
    {id:"def-variance", type:"def", q:"Définir la variance d'un système à l'équilibre", a:"Nombre de paramètres intensifs indépendants (T, P, fractions molaires...) que l'on peut fixer librement sans rompre l'équilibre : $v = c+2-\\varphi$ (règle des phases, $c$=constituants indépendants, $\\varphi$=nombre de phases)."},
    {id:"formule-K-expression", type:"formule", q:"Expression de $K^\\circ$ pour une réaction en phase gazeuse", a:"Pour $aA(g)+bB(g) \\rightleftharpoons cC(g)+dD(g)$ : $$K^\\circ = \\dfrac{(P_C/P^\\circ)^c(P_D/P^\\circ)^d}{(P_A/P^\\circ)^a(P_B/P^\\circ)^b}$$"},
    {id:"prop-lien-K-enthalpie-libre", type:"propriété", q:"Lien entre $K^\\circ$ et l'enthalpie libre standard de réaction", a:"$$\\Delta_rG^\\circ(T) = -RT\\ln K^\\circ(T)$$ Plus $K^\\circ$ est grand, plus la réaction est thermodynamiquement favorisée dans le sens direct."},
    {id:"methode-calcul-composition-equilibre", type:"méthode", q:"Méthode : déterminer la composition à l'équilibre", a:"1) Tableau d'avancement.&lt;br&gt;2) Exprimer $Q_r$ en fonction de $\\xi$ (via les activités).&lt;br&gt;3) Résoudre $Q_r(\\xi_{eq}) = K^\\circ$.&lt;br&gt;4) Vérifier que $0 \\le \\xi_{eq} \\le \\xi_{max}$ (cohérence physique)."}
  ]
});
