/* Cours : Chimie — Ch.4 : Description des molécules organiques */
window.OSCILLO_COURSES = window.OSCILLO_COURSES || [];
window.OSCILLO_COURSES.push({
  subject: "chimie",
  id: "c4",
  name: "Description des molécules organiques",
  cards: [
    {id:"def-squelette-carbone", type:"def", q:"Définir squelette carboné, chaîne linéaire/ramifiée/cyclique", a:"Ensemble des atomes de carbone liés entre eux formant l'ossature de la molécule. Linéaire : sans ramification. Ramifiée : avec chaînes latérales. Cyclique : formant un/des cycle(s)."},
    {id:"def-nomenclature-alcanes", type:"def", q:"Règles de base de nomenclature des alcanes", a:"Chaîne principale = plus longue chaîne carbonée continue. Numéroter pour donner les indices les plus petits aux substituants. Nom = préfixes des substituants (ordre alphabétique) + suffixe -ane selon le nombre de C (méthane, éthane, propane...)."},
    {id:"def-groupes-caracteristiques", type:"def", q:"Groupes caractéristiques usuels et suffixes associés", a:"Alcool -OH (-ol), amine -NH₂ (-amine), acide carboxylique -COOH (-oïque), ester -COO- (-oate), aldéhyde -CHO (-al), cétone C=O (-one), amide -CONH₂ (-amide), nitrile -C≡N (-nitrile)."},
    {id:"prop-ordre-priorite-groupes", type:"propriété", q:"Ordre de priorité des groupes caractéristiques (nomenclature)", a:"Acide carboxylique &gt; ester &gt; amide &gt; nitrile &gt; aldéhyde &gt; cétone &gt; alcool &gt; amine (du plus prioritaire, cité en suffixe, au moins prioritaire, cité en préfixe si un groupe plus prioritaire est présent)."},
    {id:"def-isomerie", type:"def", q:"Définir l'isomérie et distinguer isomérie de constitution / stéréoisomérie", a:"Isomères : même formule brute, structures différentes. Isomérie de constitution : atomes liés différemment (chaîne, position, fonction). Stéréoisomérie : même enchaînement d'atomes, disposition spatiale différente."},
    {id:"def-isomerie-constitution-types", type:"def", q:"Types d'isomérie de constitution", a:"De chaîne : squelette carboné différent. De position : groupe caractéristique à une position différente. De fonction : groupe caractéristique différent (ex. alcool/éther)."},
    {id:"def-stereoisomerie-types", type:"def", q:"Types de stéréoisomérie : configuration et conformation", a:"Stéréoisomères de configuration : ne peuvent s'interconvertir sans casser de liaison (énantiomères, diastéréoisomères Z/E ou avec plusieurs centres stéréogènes). Stéréoisomères de conformation : interconvertibles par simple rotation autour de liaisons simples."},
    {id:"def-carbone-asymetrique-chiralite", type:"def", q:"Définir carbone asymétrique et chiralité", a:"Carbone asymétrique (stéréogène) : carbone tétraédrique lié à 4 groupes tous différents. Molécule chirale : non superposable à son image dans un miroir (souvent car possède au moins un carbone asymétrique)."},
    {id:"def-enantiomeres-diastereoisomeres", type:"def", q:"Définir énantiomères et diastéréoisomères", a:"Énantiomères : stéréoisomères de configuration, images l'un de l'autre dans un miroir, non superposables (mêmes propriétés physiques sauf pouvoir rotatoire et interaction avec la lumière polarisée / autres molécules chirales). Diastéréoisomères : stéréoisomères de configuration qui ne sont pas énantiomères (propriétés physiques différentes)."},
    {id:"methode-cip-configuration", type:"méthode", q:"Méthode : déterminer la configuration R/S (règles CIP)", a:"1) Classer les 4 substituants par ordre de priorité décroissante (numéro atomique de l'atome directement lié ; en cas d'égalité, comparer les atomes suivants).&lt;br&gt;2) Placer le substituant de plus faible priorité à l'arrière.&lt;br&gt;3) Regarder le sens de rotation 1→2→3 des trois autres : horaire = R, antihoraire = S."},
    {id:"methode-cip-alcenes-ZE", type:"méthode", q:"Méthode : déterminer la configuration Z/E d'un alcène", a:"Sur chaque carbone de la double liaison, classer les deux substituants par priorité CIP. Si les deux substituants prioritaires sont du même côté : Z (zusammen). Si de part et d'autre : E (entgegen)."},
    {id:"def-representation-cram", type:"def", q:"Définir la représentation de Cram", a:"Représentation en perspective : traits pleins dans le plan, triangle plein vers l'avant, triangle hachuré vers l'arrière — pour représenter la stéréochimie 3D d'un centre tétraédrique."},
    {id:"def-representation-newman", type:"def", q:"Définir la représentation de Newman", a:"Représentation en projection le long d'une liaison C-C : atome avant = point central avec 3 liaisons, atome arrière = cercle avec 3 liaisons ; utilisée pour étudier les conformations (éclipsée, décalée)."},
    {id:"def-representation-fischer", type:"def", q:"Définir la représentation de Fischer", a:"Représentation en croix : chaîne carbonée verticale (numérotée de haut en bas), liaisons horizontales vers l'avant, liaisons verticales vers l'arrière ; utilisée notamment pour les sucres."},
    {id:"prop-conformations-ethane", type:"propriété", q:"Conformations de l'éthane : éclipsée vs décalée", a:"Décalée (staggered) : plus stable, minimise les répulsions entre liaisons C-H. Éclipsée (eclipsed) : moins stable, liaisons C-H alignées, répulsions maximales. Interconversion par simple rotation autour de la liaison C-C."},
    {id:"prop-conformations-cyclohexane", type:"propriété", q:"Conformations du cyclohexane : chaise, bateau", a:"Chaise : conformation la plus stable, tous les angles proches de 109,5°, positions axiales et équatoriales. Bateau : moins stable (tension de torsion et interactions défavorables, notamment \"flagpole\"). Interconversion possible entre deux chaises (inversion de cycle)."},
    {id:"prop-positions-axiales-equatoriales", type:"propriété", q:"Positions axiales et équatoriales (cyclohexane chaise)", a:"Substituants encombrants préfèrent la position équatoriale (moins d'interactions 1,3-diaxiales défavorables) : conformation la plus stable a le plus gros substituant en équatorial."},
    {id:"methode-identifier-carbones-asymetriques", type:"méthode", q:"Méthode : identifier tous les carbones asymétriques d'une molécule", a:"Repérer chaque carbone tétraédrique (4 liaisons simples), vérifier que ses 4 substituants sont tous différents (y compris en \"regardant plus loin\" dans la chaîne si nécessaire pour différencier deux branches similaires)."}
  ]
});
