/* Cours : Chimie — Ch.7 : Écriture des mécanismes réactionnels et réactivité des espèces organiques */
window.OSCILLO_COURSES = window.OSCILLO_COURSES || [];
window.OSCILLO_COURSES.push({
  subject: "chimie",
  id: "c7",
  name: "Mécanismes réactionnels et réactivité des espèces organiques",
  cards: [
    {id:"def-effet-inductif", type:"def", q:"Définir l'effet inductif", a:"Effet de polarisation transmis à travers les liaisons $\\sigma$, dû à une différence d'électronégativité. Effet inductif attracteur (–I) : groupe électronégatif (halogènes, O, N). Effet inductif donneur (+I) : groupe alkyle."},
    {id:"def-effet-mesomere", type:"def", q:"Définir l'effet mésomère", a:"Effet de délocalisation électronique transmis via un système $\\pi$ conjugué (doublets non liants, liaisons multiples). Mésomère donneur (+M) : doublet non liant conjugué (ex. -OH, -NH₂). Mésomère attracteur (–M) : groupe avec liaison multiple polarisée conjuguée (ex. C=O, NO₂)."},
    {id:"def-nucleophile-electrophile", type:"def", q:"Définir nucléophile et électrophile", a:"Nucléophile : espèce riche en électrons (doublet non liant ou liaison $\\pi$), capable de les donner. Électrophile : espèce pauvre en électrons, capable d'en accepter (souvent porteuse d'une charge $\\delta^+$ ou $+$)."},
    {id:"prop-nucleophilie-basicite", type:"propriété", q:"Distinguer nucléophilie et basicité", a:"Basicité : aptitude thermodynamique à capter H⁺ (comparée via $pK_a$). Nucléophilie : aptitude cinétique à attaquer un centre électrophile (dépend aussi de l'encombrement stérique et de la polarisabilité) — les deux notions sont corrélées mais pas identiques."},
    {id:"def-fleche-courbe", type:"def", q:"Définir le formalisme des flèches courbes", a:"Flèche partant d'un doublet (liant ou non liant) ou d'un électron célibataire, pointant vers l'endroit où il se déplace (nouvelle liaison ou nouveau doublet non liant) ; décrit le mouvement des électrons dans un mécanisme."},
    {id:"def-mecanisme-sn2", type:"def", q:"Définir le mécanisme $S_N2$", a:"Substitution nucléophile bimoléculaire, concertée : attaque du nucléophile en arrière du groupe partant (backside attack) simultanément à son départ, en une seule étape (état de transition unique)."},
    {id:"prop-cinetique-stereochimie-sn2", type:"propriété", q:"Cinétique et stéréochimie de $S_N2$", a:"Cinétique d'ordre 2 : $v=k[\\text{substrat}][\\text{nucléophile}]$. Stéréochimie : inversion de configuration (Walden) au centre stéréogène attaqué."},
    {id:"def-mecanisme-sn1", type:"def", q:"Définir le mécanisme $S_N1$", a:"Substitution nucléophile monomoléculaire, en deux étapes : 1) départ du groupe partant formant un carbocation (étape lente, cinétiquement déterminante), 2) attaque rapide du nucléophile sur le carbocation."},
    {id:"prop-cinetique-stereochimie-sn1", type:"propriété", q:"Cinétique et stéréochimie de $S_N1$", a:"Cinétique d'ordre 1 : $v=k[\\text{substrat}]$ (indépendante du nucléophile). Stéréochimie : racémisation (le carbocation plan est attaqué des deux côtés, mélange de configurations)."},
    {id:"prop-facteurs-sn1-vs-sn2", type:"propriété", q:"Facteurs qui favorisent $S_N1$ vs $S_N2$", a:"$S_N1$ favorisée par : substrat tertiaire (carbocation stable), solvant polaire protique, nucléophile faible. $S_N2$ favorisée par : substrat primaire (peu encombré), solvant polaire aprotique, nucléophile fort et peu encombré."},
    {id:"def-mecanisme-e1-e2", type:"def", q:"Définir les mécanismes d'élimination E1 et E2", a:"E1 : deux étapes via un carbocation (comme $S_N1$), une base arrache un H en $\\beta$ après formation du carbocation. E2 : concertée, une base arrache un H en $\\beta$ simultanément au départ du groupe partant, formant la double liaison en une étape."},
    {id:"prop-competition-substitution-elimination", type:"propriété", q:"Compétition substitution/élimination", a:"Un nucléophile fort et peu basique favorise la substitution ; une base forte et encombrée (ex. tBuOK) favorise l'élimination. La température élevée favorise également l'élimination (produit thermodynamique, plus de degrés de liberté)."},
    {id:"prop-regle-zaitsev", type:"propriété", q:"Règle de Zaïtsev", a:"Lors d'une élimination, l'alcène le plus substitué (le plus stable thermodynamiquement) est généralement le produit majoritaire."},
    {id:"def-carbocation-stabilite", type:"def", q:"Stabilité relative des carbocations", a:"Tertiaire $>$ secondaire $>$ primaire $>$ méthyle, stabilisée par effet inductif donneur (+I) des groupes alkyles et par hyperconjugaison ; encore plus stabilisée par effet mésomère donneur (+M) si un groupe adjacent possède un doublet ou une liaison $\\pi$ conjuguée."},
    {id:"prop-sites-nucleophiles-electrophiles-molecule", type:"propriété", q:"Identifier les sites nucléophiles et électrophiles dans une molécule", a:"Sites nucléophiles : atomes porteurs de doublets non liants (O, N), liaisons $\\pi$ riches (alcènes, aromatiques activés). Sites électrophiles : carbones liés à un groupe électronégatif ou portant une charge partielle $\\delta^+$ (carbone de C=O, carbone lié à un halogène)."}
  ]
});
