/* Cours : Maths — Chapitre 6 : Équations différentielles du premier ordre */
window.OSCILLO_COURSES = window.OSCILLO_COURSES || [];
window.OSCILLO_COURSES.push({
  subject: "maths",
  id: "m6",
  name: "Équations différentielles du premier ordre",
  cards: [
    {id:"def-edl1", type:"def", q:"Définir une équation différentielle linéaire du premier ordre (EDL1), le second membre et une solution", a:"Une EDL1 est une équation du type $$y'(x)+a(x)y(x)=b(x)$$ où $a$ et $b$ sont deux fonctions continues sur un intervalle $I$, $y$ est une fonction inconnue, et $b$ s'appelle le second membre. Une solution de l'EDL1 sur $I$ est une fonction $S:I\\to\\mathbb{R}$ dérivable sur $I$ telle que $$\\forall x\\in I,\\ S'(x)+a(x)S(x)=b(x)$$"},
    {id:"def-resoudre-edl1", type:"def", q:"Que signifie « résoudre une EDL1 sur $I$ » ?", a:"Résoudre une EDL1 sur $I$ c'est trouver l'ensemble de ses solutions sur $I$, i.e. toutes les fonctions $y:I\\to\\mathbb{R}$ telles que $\\forall x\\in I,\\ y'(x)+a(x)y(x)=b(x)$."},
    {id:"theoreme-fondamental-homogene", type:"propriété", q:"Énoncer le théorème fondamental homogène : ensemble des solutions de $(E_0):y'(x)+a(x)y(x)=0$", a:"Soient $I$ un intervalle de $\\mathbb{R}$, $a:I\\to\\mathbb{R}$ continue sur $I$, $A$ une primitive de $a$ sur $I$, alors l'ensemble des solutions de $(E_0)$ sur $I$ est $$\\left\\{x\\mapsto Ce^{-A(x)} \\mid C\\in\\mathbb{R}\\right\\}$$ Preuve (sens direct) : pour $y_0:x\\mapsto Ce^{-A(x)}$, $y_0'(x)+a(x)y_0(x)=-a(x)Ce^{-A(x)}+a(x)y_0(x)=0$. (Réciproque) : si $y_0$ est solution de $(E_0)$, poser $g(x)=y_0(x)e^{A(x)}$ ; alors $g'=0$ donc $g$ est constante, d'où $y_0(x)=Ce^{-A(x)}$."},
    {id:"corollaire-a-fonction-constante", type:"propriété", q:"Ensemble des solutions sur $\\mathbb{R}$ de $(E_0):y'+ay=0$ lorsque $a\\in\\mathbb{R}$ est une constante", a:"$$\\left\\{x\\mapsto Ce^{-ax} \\mid C\\in\\mathbb{R}\\right\\}$$"},
    {id:"remarque-infinite-solutions-une-constante", type:"propriété", q:"Remarque générale sur le nombre de solutions d'une équation homogène $(E_0)$", a:"$(E_0)$ admet une infinité de fonctions solutions, infinité paramétrée par une seule constante $C\\in\\mathbb{R}$."},
    {id:"theoreme-fondamental-cas-general", type:"propriété", q:"Énoncer le théorème fondamental (cas général) : ensemble des solutions de $(E):y'(x)+a(x)y(x)=b(x)$", a:"Soient $I$ un intervalle, $a,b$ continues sur $I$, $S$ une solution de $(E)$ sur $I$, $A$ une primitive de $a$ sur $I$, alors l'ensemble des solutions de $(E)$ sur $I$ est $$\\left\\{x\\mapsto Ce^{-A(x)}+S(x) \\mid C\\in\\mathbb{R}\\right\\}$$"},
    {id:"propriete-structure-solution-generale", type:"propriété", q:"Autrement dit, comment s'exprime l'ensemble des solutions de $(E)$ à partir de $S_0$ (solutions de l'équation homogène associée) et d'une solution particulière $S$ ?", a:"Si $S_0$ est l'ensemble des solutions de l'équation homogène associée à $(E)$ sur $I$, l'ensemble des solutions de $(E)$ sur $I$ est $$\\{y_0+S \\mid y_0\\in S_0\\}$$ Preuve : pour $y=y_0+S$, $y'+ay=(y_0'+ay_0)+(S'+aS)=0+b=b$ (car $y_0$ solution de l'homogène et $S$ solution de $(E)$)."},
    {id:"propriete-principe-superposition", type:"propriété", q:"Énoncer le principe de superposition des solutions", a:"Si $S_1$ est solution particulière de $(E_1):d(x)y'(x)+a(x)y(x)=b_1(x)$ sur $I$ et $S_2$ est solution particulière de $(E_2):d(x)y'(x)+a(x)y(x)=b_2(x)$ sur $I$, alors $S_1+S_2$ est solution particulière de $(E):d(x)y'(x)+a(x)y(x)=b_1(x)+b_2(x)$ sur $I$."},
    {id:"def-probleme-de-cauchy", type:"def", q:"Définir un problème de Cauchy pour une EDL1", a:"Un problème de Cauchy est un problème constitué d'une équation différentielle dont on cherche une solution vérifiant une certaine condition initiale. Pour une équation linéaire du premier ordre, il s'agit de trouver l'unique fonction $y$ définie sur un intervalle $I$ telle que $$\\begin{cases}(E):y'(x)+a(x)y(x)=b(x)\\\\ y(\\alpha)=\\beta\\end{cases}$$ où $a$ et $b$ sont continues sur $I$, $\\alpha\\in I$ et $\\beta\\in\\mathbb{R}$."},
    {id:"theoreme-cauchy-existence-unicite", type:"propriété", q:"Énoncer le théorème d'existence et d'unicité de Cauchy pour une EDL1", a:"Soient $(E):y'(x)+a(x)y(x)=b(x)$ avec $I$ intervalle de $\\mathbb{R}$, $a,b$ continues sur $I$, $\\alpha\\in I$, $\\beta\\in\\mathbb{R}$, alors il existe une et une seule solution de $(E)$ sur $I$, $y$, telle que $$y(\\alpha)=\\beta$$"},
    {id:"propriete-courbes-solutions-ne-se-croisent-pas", type:"propriété", q:"Conséquence géométrique du théorème de Cauchy sur les courbes des solutions de $(E)$", a:"Les courbes des solutions de $(E)$ ne se croisent pas (par deux points distincts d'abscisse $\\alpha$ ne peuvent passer deux solutions différentes de $(E)$, sinon l'unicité de Cauchy serait violée)."},
    {id:"methode-principe-du-mimetisme", type:"méthode", q:"Méthode du principe du mimétisme pour trouver une solution particulière", a:"Le principe du mimétisme consiste à chercher une solution particulière de l'équation générale de la même forme que le second membre de l'équation (ex : second membre polynomial → chercher une solution polynomiale de même degré ; second membre en $e^{\\lambda x}$ → chercher une solution en $Ke^{\\lambda x}$, etc.). C'est la méthode à utiliser en priorité."},
    {id:"methode-superposition-des-solutions", type:"méthode", q:"Méthode de superposition des solutions : quand l'utiliser ?", a:"Si le second membre d'une EDL1 est la somme de fonctions de natures différentes (ex : $b(x)=b_1(x)+b_2(x)$), il faut utiliser le principe de superposition des solutions afin de trouver une solution particulière de l'équation : on cherche séparément une solution particulière $S_1$ de l'équation à second membre $b_1$, une solution particulière $S_2$ de l'équation à second membre $b_2$, puis $S_1+S_2$ est solution particulière de l'équation complète."},
    {id:"methode-variation-de-la-constante", type:"méthode", q:"Méthode de variation de la constante (rédaction type) pour résoudre $(E):d(x)y'(x)+a(x)y(x)=b(x)$", a:"À utiliser si le principe du mimétisme ne s'applique pas, sachant que l'ensemble des solutions de l'homogène est $\\{x\\mapsto C\\cdot e^{-A(x)} \\mid C\\in\\mathbb{R}\\}$ :<br>1. Poser $S:x\\mapsto C(x)\\cdot e^{-A(x)}$ avec $C:I\\to\\mathbb{R}$ dérivable sur $I$ (fonction, plus constante). $S$ est dérivable et on calcule $S'(x)$.<br>2. Traduire « $S$ est solution de $(E)$ sur $I$ » $\\iff \\forall x\\in I,\\ d(x)S'(x)+a(x)S(x)=b(x)$, remplacer $S'(x)$ et $S(x)$ et simplifier : les termes en $C(x)$ doivent disparaître (sinon il y a une erreur), il doit rester $\\iff \\forall x\\in I,\\ C'(x)=h(x)$.<br>3. Trouver une primitive $H$ de $h$ sur $I$.<br>4. Conclure que $S:x\\mapsto H(x)\\cdot e^{-A(x)}$ est une solution de $(E)$ sur $I$, puis donner l'ensemble des solutions de l'équation générale grâce au théorème fondamental."},
  ]
});
