/* Cours : Mathématiques — Ch.16 : Analyse asymptotique */
window.OSCILLO_COURSES = window.OSCILLO_COURSES || [];
window.OSCILLO_COURSES.push({
  subject: "maths",
  id: "m16",
  name: "Analyse asymptotique",
  cards: [
    {id:"def-O-o-equivalent", type:"def", q:"Définir $O$ (grand O), $o$ (petit o), $\\sim$ (équivalent)", a:"$u_n = O(v_n)$ : $\\exists K, |u_n|\\le K|v_n|$ à partir d'un rang.&lt;br&gt;$u_n=o(v_n)$ : $u_n/v_n \\to 0$.&lt;br&gt;$u_n \\sim v_n$ : $u_n/v_n \\to 1$ (ou $u_n-v_n=o(v_n)$)."},
    {id:"def-suite-dominee", type:"def", q:"Définir suite dominée par une autre", a:"$(u_n)$ dominée par $(v_n)$ signifie $u_n=O(v_n)$."},
    {id:"def-suite-negligeable", type:"def", q:"Définir suite négligeable devant une autre", a:"$(u_n)$ négligeable devant $(v_n)$ signifie $u_n=o(v_n)$."},
    {id:"def-suite-equivalente", type:"def", q:"Définir suites équivalentes", a:"$u_n\\sim v_n$ ssi $u_n=v_n+o(v_n)$, ou de façon équivalente $u_n/v_n\\to1$ (pour $v_n\\ne0$ à partir d'un certain rang)."},
    {id:"def-DL", type:"def", q:"Définir développement limité (DL) à l'ordre $n$ en $x_0$", a:"$f$ admet un DL d'ordre $n$ en $x_0$ s'il existe $a_0,\\dots,a_n$ tels que $f(x) = a_0+a_1(x-x_0)+\\cdots+a_n(x-x_0)^n + o((x-x_0)^n)$."},
    {id:"prop-relation-equivalence-sim", type:"propriété", q:"Réflexivité, symétrie, transitivité de $\\sim$", a:"$\\sim$ est une relation d'équivalence : $u_n\\sim u_n$ ; $u_n\\sim v_n \\Rightarrow v_n\\sim u_n$ ; $u_n\\sim v_n, v_n\\sim w_n \\Rightarrow u_n\\sim w_n$."},
    {id:"prop-equivalent-limite", type:"propriété", q:"Équivalent et limite (même limite ou comportement)", a:"Si $u_n\\sim v_n$ et $v_n\\to\\ell$, alors $u_n\\to\\ell$ (même limite, y compris infinie ; en particulier même signe à partir d'un certain rang)."},
    {id:"methode-recherche-equivalent", type:"méthode", q:"Méthode : rechercher un équivalent (via régularité de f)", a:"Si $f$ dérivable en $x_0$ avec $f'(x_0)\\ne0$ : $f(x)-f(x_0) \\sim f'(x_0)(x-x_0)$ (taux d'accroissement). Sinon utiliser un DL ou factoriser par le terme dominant."},
    {id:"prop-operations-O-o", type:"propriété", q:"Opérations sur les $O$ et $o$", a:"$o(v_n)+o(v_n)=o(v_n)$ ; $O(v_n)+O(v_n)=O(v_n)$ ; $u_n\\cdot o(v_n) = o(u_nv_n)$ ; produit/quotient d'équivalents : compatible avec $\\sim$."},
    {id:"prop-lien-o-equivalent", type:"propriété", q:"Lien entre $o$ et $\\sim$", a:"$u_n \\sim v_n \\iff u_n - v_n = o(v_n) \\iff u_n = v_n + o(v_n)$"},
    {id:"prop-composition-equivalents", type:"propriété", q:"Composition d'équivalents (avec précaution)", a:"$u_n\\sim v_n \\Rightarrow u_n^\\alpha \\sim v_n^\\alpha$ (pour $\\alpha$ fixé, $u_n,v_n>0$). ATTENTION : ne pas composer un équivalent avec $\\exp$, $\\ln$, ou une somme directement sans précaution."},
    {id:"prop-equivalent-exp-ln", type:"propriété", q:"Équivalents et exp / ln", a:"$u_n\\sim v_n \\centernot\\Rightarrow e^{u_n}\\sim e^{v_n}$ (FAUX en général). Mais $\\ln(1+u_n)\\sim u_n$ si $u_n\\to0$, et $u_n\\to\\ell\\ne0,1 \\Rightarrow \\ln(u_n)-\\ln(v_n)=o(1)$ si $u_n\\sim v_n$ (différence, pas quotient)."},
    {id:"formulaire-equivalents-usuels", type:"formule", q:"Équivalents usuels en 0 (via DL1)", a:"$\\sin x \\sim x$ ; $\\tan x \\sim x$ ; $1-\\cos x \\sim \\dfrac{x^2}{2}$ ; $\\ln(1+x)\\sim x$ ; $e^x-1\\sim x$ ; $(1+x)^\\alpha - 1 \\sim \\alpha x$"},
    {id:"prop-equivalent-fonction-polynomiale", type:"propriété", q:"Équivalent en $\\pm\\infty$ d'une fonction polynomiale", a:"En $\\pm\\infty$, un polynôme est équivalent à son terme de plus haut degré : $a_nx^n+\\cdots+a_0 \\sim a_nx^n$."},
    {id:"def-o-classique-echelle", type:"def", q:"Échelle de comparaison classique en $+\\infty$", a:"En $+\\infty$ : $\\ln^\\beta x = o(x^\\alpha)$ pour $\\alpha>0$, et $x^\\alpha = o(e^{\\gamma x})$ pour $\\gamma>0$ (croissances comparées : puissance $\\ll$ exponentielle, log $\\ll$ puissance)."},
    {id:"formule-taylor-young", type:"formule", q:"Formule de Taylor-Young", a:"Si $f$ est $C^n$ au voisinage de $x_0$ : $$f(x) = \\sum_{k=0}^n \\dfrac{f^{(k)}(x_0)}{k!}(x-x_0)^k + o((x-x_0)^n)$$"},
    {id:"prop-dl-usuels", type:"propriété", q:"Développements limités usuels en 0 (rappel)", a:"$e^x = 1+x+\\frac{x^2}{2!}+\\cdots+\\frac{x^n}{n!}+o(x^n)$&lt;br&gt;$\\dfrac{1}{1-x} = 1+x+x^2+\\cdots+x^n+o(x^n)$&lt;br&gt;$\\ln(1+x) = x-\\frac{x^2}{2}+\\cdots+(-1)^{n-1}\\frac{x^n}{n}+o(x^n)$&lt;br&gt;$(1+x)^\\alpha = 1+\\alpha x+\\frac{\\alpha(\\alpha-1)}{2}x^2+\\cdots+o(x^n)$"},
    {id:"prop-unicite-DL", type:"propriété", q:"Unicité du DL", a:"Si $f$ admet un DL d'ordre $n$ en $x_0$, celui-ci est unique."},
    {id:"prop-parite-DL", type:"propriété", q:"Parité et DL", a:"Si $f$ paire (resp. impaire) et admet un DL en $0$, ce DL ne contient que des termes de degré pair (resp. impair)."},
    {id:"prop-CNS-DL0-DL1", type:"propriété", q:"CNS pour l'existence de DL0 et DL1", a:"$f$ admet un DL0 en $x_0$ ssi $f$ est continue (ou prolongeable par continuité) en $x_0$. $f$ admet un DL1 en $x_0$ ssi $f$ est dérivable (ou prolongeable en une fonction dérivable) en $x_0$."},
    {id:"prop-operations-DL", type:"propriété", q:"Opérations sur les DL : combinaison linéaire, produit, inverse, quotient", a:"On combine/multiplie/divise les DL en tronquant au bon ordre. Pour l'inverse d'un DL commençant par une constante non nulle $a_0$ : $\\frac{1}{a_0+u} = \\frac{1}{a_0}\\cdot\\frac{1}{1+u/a_0}$, développer via $\\frac{1}{1-t}$."},
    {id:"methode-primitivation-derivation-DL", type:"méthode", q:"Méthode : primitivation / dérivation d'un DL", a:"Primitivation : intégrer terme à terme le DL d'ordre $n$ de $f'$ pour obtenir un DL d'ordre $n+1$ de $f$ (en ajustant la constante avec $f(x_0)$). Dérivation : possible seulement sous hypothèses supplémentaires (la dérivée doit elle-même être régulière), à utiliser avec précaution."},
    {id:"methode-suite-un-vn-n", type:"méthode", q:"Méthode : étudier $\\left(\\dfrac{u_n}{v_n}\\right)^n$ ou formes similaires", a:"Passer par l'exponentielle du logarithme : $\\left(\\frac{u_n}{v_n}\\right)^n = e^{n\\ln(u_n/v_n)}$, puis utiliser un DL de $\\ln(1+x)$ si $u_n/v_n\\to1$."},
    {id:"methode-calcul-rapide-1px-alpha", type:"méthode", q:"Calcul rapide via le DL de $(1+x)^\\alpha$", a:"Pour des racines/puissances au voisinage de valeurs connues, factoriser pour se ramener à $(1+\\varepsilon)^\\alpha$ avec $\\varepsilon\\to0$, puis utiliser $(1+\\varepsilon)^\\alpha \\approx 1+\\alpha\\varepsilon$ (ou ordre supérieur si besoin)."},
    {id:"methode-manipulation-o-xk", type:"méthode", q:"Méthode : manipuler les $o$ par multiplication par $x^k$", a:"$x^k \\cdot o(x^n) = o(x^{n+k})$ : utile pour ajuster l'ordre d'un DL après multiplication par un facteur $x^k$."},
    {id:"methode-recherche-equivalent-DL", type:"méthode", q:"Méthode : rechercher un équivalent via un DL", a:"Faire un DL suffisamment poussé jusqu'au premier terme non nul : cet terme donne l'équivalent recherché."},
    {id:"methode-etude-limite-forme-indeterminee", type:"méthode", q:"Méthode : étudier une limite avec forme indéterminée via équivalents/DL", a:"Remplacer chaque terme par son équivalent (produits/quotients uniquement, pas de sommes/différences directement), ou faire un DL à l'ordre suffisant pour lever l'indétermination."},
    {id:"methode-etude-locale-courbe", type:"méthode", q:"Méthode : étude locale d'une courbe via DL (tangente, position)", a:"Le DL à l'ordre 1 donne l'équation de la tangente ($y=a_0+a_1(x-x_0)$). Le premier terme d'ordre $\\ge2$ non nul donne la position de la courbe par rapport à la tangente (signe du terme)."}
  ]
});
