/* Cours : Mathématiques — Ch.26 : Les variables aléatoires */
window.OSCILLO_COURSES = window.OSCILLO_COURSES || [];
window.OSCILLO_COURSES.push({
  subject: "maths",
  id: "m26",
  name: "Les variables aléatoires",
  cards: [
    {id:"def-variable-aleatoire", type:"def", q:"Définir une variable aléatoire", a:"Application $X:\\Omega\\to E$ (souvent $E=\\mathbb R$), définie sur un univers $\\Omega$ muni d'une probabilité."},
    {id:"def-loi-variable-aleatoire", type:"def", q:"Définir la loi d'une variable aléatoire", a:"Application qui à chaque valeur $x_i$ prise par $X$ associe $P(X=x_i)$ ; détermine entièrement le comportement probabiliste de $X$."},
    {id:"def-composee-fX", type:"def", q:"Définir la composée $f(X)$", a:"Pour $f:E\\to F$ et $X$ va sur $\\Omega$ : $f(X): \\omega \\mapsto f(X(\\omega))$, nouvelle variable aléatoire."},
    {id:"def-loi-conditionnelle", type:"def", q:"Définir la loi conditionnelle de $X$ sachant $A$", a:"Loi de $X$ calculée avec la probabilité conditionnelle $P_A$ : $P_A(X=x_i) = P(X=x_i \\mid A)$."},
    {id:"def-loi-uniforme", type:"def", q:"Définir la loi uniforme $\\mathcal U(E)$", a:"Pour $E$ fini de cardinal $n$ : $P(X=x) = \\dfrac1n$ pour chaque $x\\in E$ (équiprobabilité)."},
    {id:"def-esperance", type:"def", q:"Définir l'espérance d'une variable aléatoire", a:"$$E(X) = \\sum_i x_i P(X=x_i)$$ (moyenne pondérée par les probabilités)."},
    {id:"def-loi-bernoulli", type:"def", q:"Définir la loi de Bernoulli $\\mathcal B(p)$", a:"$X\\in\\{0,1\\}$ avec $P(X=1)=p$, $P(X=0)=1-p$. $E(X)=p$, $V(X)=p(1-p)$."},
    {id:"def-loi-binomiale", type:"def", q:"Définir la loi binomiale $\\mathcal B(n,p)$", a:"Nombre de succès dans $n$ répétitions indépendantes d'une épreuve de Bernoulli de paramètre $p$ : $P(X=k)=\\binom{n}{k}p^k(1-p)^{n-k}$, $k\\in\\llbracket0,n\\rrbracket$."},
    {id:"def-couple-n-uplet-va", type:"def", q:"Définir couple / n-uplet de variables aléatoires", a:"$(X,Y)$ (ou $(X_1,\\dots,X_n)$) : application $\\Omega \\to E\\times F$ (ou $E_1\\times\\cdots\\times E_n$) regroupant plusieurs variables aléatoires définies sur le même univers."},
    {id:"def-loi-conjointe-marginale", type:"def", q:"Définir loi conjointe et lois marginales", a:"Loi conjointe de $(X,Y)$ : $P(X=x_i,Y=y_j)$. Lois marginales : lois de $X$ seule et de $Y$ seule, obtenues en sommant sur l'autre variable."},
    {id:"def-variable-centree", type:"def", q:"Définir une variable aléatoire centrée", a:"$X$ centrée si $E(X)=0$."},
    {id:"def-esperance-produit-moment", type:"def", q:"Définir moment d'ordre $k$", a:"$E(X^k)$ : moment d'ordre $k$ de $X$ (moment d'ordre 1 = espérance)."},
    {id:"def-variance-ecart-type", type:"def", q:"Définir variance et écart-type", a:"$V(X) = E((X-E(X))^2)$. Écart-type : $\\sigma(X) = \\sqrt{V(X)}$."},
    {id:"def-variable-reduite", type:"def", q:"Définir une variable réduite", a:"$X$ réduite si $V(X)=1$."},
    {id:"def-variable-centree-reduite", type:"def", q:"Définir la variable centrée réduite associée à $X$", a:"$X^* = \\dfrac{X-E(X)}{\\sigma(X)}$ (si $\\sigma(X)\\ne0$), vérifie $E(X^*)=0$, $V(X^*)=1$."},
    {id:"def-covariance", type:"def", q:"Définir la covariance", a:"$$\\mathrm{Cov}(X,Y) = E((X-E(X))(Y-E(Y))) = E(XY)-E(X)E(Y)$$"},
    {id:"def-variables-decorrelees", type:"def", q:"Définir des variables décorrélées", a:"$X,Y$ décorrélées si $\\mathrm{Cov}(X,Y)=0$."},
    {id:"prop-equivalence-composee-loi", type:"propriété", q:"Équivalence et composée : loi de $f(X)$", a:"$P(f(X)=y) = \\sum_{x, f(x)=y} P(X=x)$ (somme sur tous les antécédents de $y$ par $f$)."},
    {id:"prop-couple-lois-marginales", type:"propriété", q:"Couple de va et lois marginales", a:"Connaître la loi conjointe détermine les lois marginales, mais pas l'inverse en général (sauf indépendance)."},
    {id:"formule-esperance-Bp-Bnp", type:"formule", q:"Espérance et variance de Bernoulli / binomiale", a:"$\\mathcal B(p)$ : $E(X)=p$, $V(X)=p(1-p)$&lt;br&gt;$\\mathcal B(n,p)$ : $E(X)=np$, $V(X)=np(1-p)$"},
    {id:"prop-loi-conjointe-nuplet", type:"propriété", q:"Loi conjointe d'un $n$-uplet", a:"$P(X_1=x_1,\\dots,X_n=x_n)$ : détermine toutes les lois marginales et permet de définir l'indépendance."},
    {id:"prop-independance-bernoulli-binomiale", type:"propriété", q:"Indépendance et somme de variables de Bernoulli", a:"Si $X_1,\\dots,X_n$ i.i.d. de loi $\\mathcal B(p)$, alors $X_1+\\cdots+X_n$ suit une loi $\\mathcal B(n,p)$."},
    {id:"prop-independance-variables", type:"propriété", q:"Définir l'indépendance de variables aléatoires", a:"$X,Y$ indépendantes si $\\forall x,y, P(X=x,Y=y)=P(X=x)P(Y=y)$ (la loi conjointe est le produit des marginales)."},
    {id:"lemme-coalition", type:"propriété", q:"Lemme des coalitions", a:"Si $X_1,\\dots,X_n$ mutuellement indépendantes, toute fonction des $X_i$ d'un groupe est indépendante de toute fonction des $X_j$ d'un groupe disjoint."},
    {id:"prop-esperance-lineaire", type:"propriété", q:"Linéarité de l'espérance", a:"$$E(aX+bY) = aE(X)+bE(Y)$$ (toujours vraie, MÊME sans indépendance)."},
    {id:"formule-transfert", type:"formule", q:"Formule de transfert", a:"$$E(f(X)) = \\sum_i f(x_i)P(X=x_i)$$ (calcule $E(f(X))$ sans connaître la loi de $f(X)$)."},
    {id:"formule-transfert-couple", type:"formule", q:"Formule de transfert pour un couple / n-uplet", a:"$$E(f(X,Y)) = \\sum_{i,j} f(x_i,y_j)\\,P(X=x_i,Y=y_j)$$"},
    {id:"prop-esperance-produit-independantes", type:"propriété", q:"Espérance d'un produit de variables indépendantes", a:"Si $X,Y$ indépendantes : $E(XY)=E(X)E(Y)$ (FAUX en général sans indépendance)."},
    {id:"formule-koenig-huygens", type:"formule", q:"Formule de König-Huygens", a:"$$V(X) = E(X^2) - E(X)^2$$"},
    {id:"prop-non-linearite-variance", type:"propriété", q:"Non-linéarité de la variance", a:"$V(aX+b) = a^2V(X)$ (attention : la variance n'est PAS linéaire, contrairement à l'espérance, à cause du carré)."},
    {id:"prop-variance-nulle", type:"propriété", q:"Variance nulle", a:"$V(X)=0 \\iff X$ est presque sûrement constante (égale à $E(X)$)."},
    {id:"prop-covariance-esperance-produit", type:"propriété", q:"Relation entre covariance et espérance du produit", a:"$$\\mathrm{Cov}(X,Y) = E(XY)-E(X)E(Y)$$"},
    {id:"prop-independance-decorrelation", type:"propriété", q:"Indépendance $\\Rightarrow$ décorrélation", a:"Si $X,Y$ indépendantes, alors $\\mathrm{Cov}(X,Y)=0$ (décorrélées). RÉCIPROQUE FAUSSE en général."},
    {id:"formule-variance-somme", type:"formule", q:"Variance d'une somme de deux variables", a:"$$V(X+Y) = V(X)+V(Y)+2\\mathrm{Cov}(X,Y)$$ Si $X,Y$ indépendantes (ou juste décorrélées) : $V(X+Y)=V(X)+V(Y)$."},
    {id:"formule-variance-somme-n", type:"formule", q:"Variance d'une somme de $n$ variables (indépendantes)", a:"Si $X_1,\\dots,X_n$ deux à deux indépendantes (ou décorrélées) : $$V\\left(\\sum_{i=1}^n X_i\\right) = \\sum_{i=1}^n V(X_i)$$"},
    {id:"inegalite-markov", type:"propriété", q:"Inégalité de Markov", a:"Pour $X\\ge0$ et $a>0$ : $$P(X\\ge a) \\le \\dfrac{E(X)}{a}$$"},
    {id:"inegalite-bienayme-tchebychev", type:"propriété", q:"Inégalité de Bienaymé-Tchebychev", a:"Pour $\\varepsilon>0$ : $$P(|X-E(X)|\\ge\\varepsilon) \\le \\dfrac{V(X)}{\\varepsilon^2}$$"},
    {id:"inegalite-concentration", type:"propriété", q:"Inégalité de concentration (idée générale)", a:"Regroupe les inégalités type Markov/Bienaymé-Tchebychev qui bornent la probabilité qu'une variable aléatoire s'écarte significativement de sa valeur moyenne/typique."}
  ]
});
