/* Cours : Mathématiques — Ch.12 : Continuité et dérivabilité : étude locale */
window.OSCILLO_COURSES = window.OSCILLO_COURSES || [];
window.OSCILLO_COURSES.push({
  subject: "maths",
  id: "m12",
  name: "Continuité et dérivabilité : étude locale",
  cards: [
    {id:"def-voisinage", type:"def", q:"Définir un voisinage d'un point", a:"$V$ est un voisinage de $x_0$ s'il existe $\\alpha>0$ tel que $]x_0-\\alpha,x_0+\\alpha[\\subset V$."},
    {id:"def-propriete-localement-vraie", type:"def", q:"Définir \"vraie au voisinage de\" / \"pour tout x assez proche de\"", a:"Une propriété $P(x)$ est vraie au voisinage de $x_0$ s'il existe $\\alpha>0$ tel que $P(x)$ est vraie pour tout $x\\in]x_0-\\alpha,x_0+\\alpha[$."},
    {id:"def-continuite-point", type:"def", q:"Définir la continuité en un point", a:"$f$ continue en $x_0$ si $\\displaystyle\\lim_{x\\to x_0} f(x) = f(x_0)$."},
    {id:"def-prolongement-continuite", type:"def", q:"Définir le prolongement par continuité", a:"Si $f$ n'est pas définie en $x_0$ mais admet une limite finie $\\ell$ en $x_0$, on prolonge $f$ en posant $f(x_0)=\\ell$ ; le prolongement est alors continu en $x_0$."},
    {id:"def-continuite-gauche-droite", type:"def", q:"Définir continuité à gauche et à droite", a:"Continue à gauche en $x_0$ : $\\lim_{x\\to x_0^-} f(x)=f(x_0)$. Continue à droite : $\\lim_{x\\to x_0^+}f(x)=f(x_0)$. Continue en $x_0$ ssi les deux."},
    {id:"def-continuite-globale", type:"def", q:"Définir la continuité globale (sur un intervalle)", a:"$f$ continue sur $I$ si $f$ est continue en tout point de $I$."},
    {id:"def-taux-accroissement-derivabilite", type:"def", q:"Définir taux d'accroissement, dérivabilité en un point et sur un intervalle", a:"Taux d'accroissement en $x_0$ : $\\dfrac{f(x)-f(x_0)}{x-x_0}$. $f$ dérivable en $x_0$ si ce taux admet une limite finie quand $x\\to x_0$, notée $f'(x_0)$."},
    {id:"def-derivabilite-gauche-droite", type:"def", q:"Définir dérivabilité à gauche et à droite", a:"Limites à gauche/droite du taux d'accroissement. $f$ dérivable en $x_0$ ssi dérivable à gauche et à droite avec les mêmes valeurs."},
    {id:"def-derivee-nieme", type:"def", q:"Définir la fonction dérivée $n$-ième", a:"$f^{(n)} = (f^{(n-1)})'$, dérivée de la dérivée $(n-1)$-ième, avec $f^{(0)}=f$."},
    {id:"def-limite-fonction-complexe", type:"def", q:"Définir la limite d'une fonction complexe", a:"Pour $f=g+ih$ à valeurs complexes, $f(x)\\to\\ell=\\ell_1+i\\ell_2$ ssi $g(x)\\to\\ell_1$ et $h(x)\\to\\ell_2$ (équivalent à $|f(x)-\\ell|\\to0$)."},
    {id:"def-fonction-complexe-bornee", type:"def", q:"Définir une fonction complexe bornée", a:"$f$ bornée sur $I$ s'il existe $K$ tel que $\\forall x\\in I, |f(x)|\\le K$."},
    {id:"def-continuite-fonction-complexe", type:"def", q:"Définir continuité d'une fonction complexe (en un point, globale)", a:"$f=g+ih$ continue en $x_0$ ssi $g$ et $h$ continues en $x_0$. Idem pour continuité globale sur $I$."},
    {id:"def-derivation-fonction-complexe", type:"def", q:"Définir la dérivation d'une fonction complexe", a:"$f=g+ih$ dérivable en $x_0$ ssi $g,h$ dérivables en $x_0$, avec $f'=g'+ih'$."},
    {id:"def-derivee-composee-exp-complexe", type:"def", q:"Dérivée de $x\\mapsto e^{\\varphi(x)}$ avec $\\varphi$ complexe", a:"Pour $\\varphi$ dérivable à valeurs complexes : $\\left(e^{\\varphi(x)}\\right)' = \\varphi'(x)e^{\\varphi(x)}$ (même formule qu'en réel)."},
    {id:"prop-ecriture-limite-voisinage", type:"propriété", q:"Écriture de la limite en termes de voisinage", a:"$f(x)\\to\\ell$ quand $x\\to x_0$ ssi pour tout voisinage $V$ de $\\ell$, il existe un voisinage $U$ de $x_0$ tel que $f(U)\\subset V$."},
    {id:"prop-unicite-limite", type:"propriété", q:"Unicité de la limite", a:"Si une fonction admet une limite en un point, celle-ci est unique."},
    {id:"prop-limite-fonction-nulle", type:"propriété", q:"Limite où la fonction s'annule dans un quotient", a:"Si $f(x_0)=0$ pour un dénominateur, étudier soigneusement le signe/comportement au voisinage (souvent forme indéterminée $0/0$ à factoriser)."},
    {id:"prop-limite-finie-bornee", type:"propriété", q:"Limite finie implique fonction bornée au voisinage", a:"Si $f$ admet une limite finie en $x_0$, alors $f$ est bornée au voisinage de $x_0$."},
    {id:"prop-passage-limite-inegalites", type:"propriété", q:"Passage à la limite dans les inégalités (fonctions)", a:"Si $f\\le g$ au voisinage de $x_0$ et $f\\to\\ell$, $g\\to\\ell'$, alors $\\ell\\le\\ell'$."},
    {id:"prop-operations-limites-fonctions", type:"propriété", q:"Opérations sur les limites de fonctions, composition, changement de variable", a:"Mêmes règles que pour les suites (somme, produit, quotient, formes indéterminées). Composition : si $f(x)\\to y_0$ et $g(y)\\to\\ell$ quand $y\\to y_0$, alors $g(f(x))\\to\\ell$."},
    {id:"thm-limite-finie-encadrement", type:"propriété", q:"Théorème de limite finie par encadrement (gendarmes, fonctions)", a:"Si $f\\le h\\le g$ au voisinage de $x_0$ et $f,g\\to\\ell$, alors $h\\to\\ell$."},
    {id:"prop-limite-infinie-minoration-fonction", type:"propriété", q:"Limite $+\\infty/-\\infty$ par minoration/majoration (fonctions)", a:"Si $f\\ge g$ au voisinage de $x_0$ et $g\\to+\\infty$, alors $f\\to+\\infty$ (symétrique)."},
    {id:"thm-domination", type:"propriété", q:"Théorème de domination (limite via encadrement type $|f(x)-\\ell|\\le \\varphi(x)$)", a:"Si $|f(x)-\\ell| \\le \\varphi(x)$ au voisinage de $x_0$ avec $\\varphi(x)\\to0$, alors $f(x)\\to\\ell$."},
    {id:"prop-bornee-tend-zero-fonction", type:"propriété", q:"Fonction bornée × fonction qui tend vers 0", a:"Si $f$ bornée au voisinage de $x_0$ et $g(x)\\to0$, alors $f(x)g(x)\\to0$."},
    {id:"prop-caracterisation-sequentielle-limite", type:"propriété", q:"Caractérisation séquentielle de la limite d'une fonction", a:"$f(x)\\to\\ell$ quand $x\\to x_0$ ssi pour toute suite $(u_n)\\to x_0$ (avec $u_n\\ne x_0$), $f(u_n)\\to\\ell$. Permet de prouver une non-limite via deux suites donnant des limites différentes."},
    {id:"thm-limite-monotone-fonction", type:"propriété", q:"Théorème de la limite monotone (fonctions)", a:"Une fonction monotone sur un intervalle admet une limite (finie ou infinie) en chaque borne de l'intervalle."},
    {id:"prop-continuite-limite-caracterisation", type:"propriété", q:"Lien continuité et limite", a:"$f$ continue en $x_0$ ssi $\\lim_{x\\to x_0} f(x)$ existe et vaut $f(x_0)$."},
    {id:"prop-caracterisation-sequentielle-continuite", type:"propriété", q:"Caractérisation séquentielle de la continuité en un point", a:"$f$ continue en $x_0$ ssi pour toute suite $(u_n)\\to x_0$, $f(u_n)\\to f(x_0)$."},
    {id:"thm-equation-tangente", type:"propriété", q:"Équation de la tangente au graphe en un point", a:"Si $f$ dérivable en $x_0$, la tangente en $(x_0,f(x_0))$ a pour équation : $y = f(x_0)+f'(x_0)(x-x_0)$."},
    {id:"prop-derivabilite-continuite", type:"propriété", q:"Dérivabilité $\\Rightarrow$ continuité", a:"Si $f$ est dérivable en $x_0$, alors $f$ est continue en $x_0$ (réciproque fausse, ex. $|x|$ en 0)."},
    {id:"prop-operations-derivees-usuelles", type:"propriété", q:"Opérations sur les dérivées : somme, produit, quotient, composée", a:"$(f+g)'=f'+g'$&lt;br&gt;$(fg)'=f'g+fg'$&lt;br&gt;$(f/g)'=\\dfrac{f'g-fg'}{g^2}$&lt;br&gt;$(g\\circ f)' = f'\\times(g'\\circ f)$"},
    {id:"thm-derivee-produit-cn", type:"propriété", q:"Formule de Leibniz : $(fg)^{(n)}$", a:"$$(fg)^{(n)} = \\sum_{k=0}^n \\binom{n}{k} f^{(k)}g^{(n-k)}$$"},
    {id:"def-classe-Cn", type:"def", q:"Définir classe $C^1$, $C^n$, $C^\\infty$", a:"$C^1$ : dérivable, dérivée continue. $C^n$ : dérivable $n$ fois, $f^{(n)}$ continue. $C^\\infty$ : dérivable indéfiniment (toutes dérivées existent)."},
    {id:"prop-continuite-derivee-reciproque", type:"propriété", q:"Continuité et dérivée de la fonction réciproque", a:"Si $f:I\\to J$ bijective et continue, alors $f^{-1}$ est continue sur $J$. Si $f$ dérivable en $x_0$ avec $f'(x_0)\\ne0$, $f^{-1}$ est dérivable en $f(x_0)$ (voir Ch.2)."},
    {id:"prop-tangente-reciproque", type:"propriété", q:"Tangente au graphe de la fonction réciproque", a:"La tangente au graphe de $f^{-1}$ au point $(y_0,x_0)$ est symétrique (par rapport à $y=x$) de la tangente à $f$ en $(x_0,y_0)$."}
  ]
});
