/* Cours : Mathématiques — Ch.13 : Les polynômes */
window.OSCILLO_COURSES = window.OSCILLO_COURSES || [];
window.OSCILLO_COURSES.push({
  subject: "maths",
  id: "m13",
  name: "Les polynômes",
  cards: [
    {id:"def-polynome-monome-coefficient", type:"def", q:"Définir polynôme, monôme, coefficient", a:"Polynôme : $P=\\sum_{k=0}^n a_kX^k$, $a_k\\in K$. Monôme : $a_kX^k$. Les $a_k$ sont les coefficients."},
    {id:"def-operations-polynomes", type:"def", q:"Définir égalité, combinaison linéaire, produit, composition de polynômes", a:"Égalité : mêmes coefficients. Combinaison linéaire : $\\lambda P+\\mu Q$. Produit : $(PQ)(X)$ obtenu par distributivité. Composée : $P(Q(X))$."},
    {id:"def-fonction-polynomiale", type:"def", q:"Définir la fonction polynomiale associée", a:"$\\tilde P : x \\mapsto \\sum a_kx^k$, fonction de $K$ dans $K$ associée au polynôme formel $P$."},
    {id:"def-degre-coefficient-dominant", type:"def", q:"Définir degré et coefficient dominant", a:"$\\deg P$ : plus grand $k$ tel que $a_k\\ne0$ (par convention $\\deg 0=-\\infty$). Coefficient dominant : $a_{\\deg P}$."},
    {id:"def-polynome-unitaire", type:"def", q:"Définir un polynôme unitaire", a:"Polynôme dont le coefficient dominant vaut $1$."},
    {id:"def-Kn-X", type:"def", q:"Définir $K_n[X]$", a:"$K_n[X] = \\{P \\in K[X] \\mid \\deg P \\le n\\}$, ensemble des polynômes de degré au plus $n$."},
    {id:"def-diviseur-multiple-polynome", type:"def", q:"Définir diviseur et multiple d'un polynôme", a:"$A$ divise $B$ (noté $A|B$) s'il existe $Q$ tel que $B=AQ$."},
    {id:"def-division-euclidienne-polynome", type:"def", q:"Définir la division euclidienne de polynômes", a:"Pour $A,B\\in K[X]$, $B\\ne0$, il existe un unique couple $(Q,R)$ tel que $A=BQ+R$ avec $\\deg R < \\deg B$."},
    {id:"def-racine-zero", type:"def", q:"Définir racine (ou zéro) d'un polynôme", a:"$a$ est racine de $P$ si $P(a)=0$, équivalent à $(X-a) | P$."},
    {id:"def-ordre-multiplicite-racine", type:"def", q:"Définir ordre de multiplicité d'une racine", a:"$a$ est racine d'ordre $k$ (multiplicité $k$) si $(X-a)^k | P$ mais $(X-a)^{k+1} \\nmid P$."},
    {id:"def-polynome-derive", type:"def", q:"Définir le polynôme dérivé", a:"Pour $P=\\sum a_kX^k$ : $P'=\\sum_{k\\ge1} ka_kX^{k-1}$."},
    {id:"def-polynome-scinde", type:"def", q:"Définir un polynôme scindé", a:"$P$ scindé sur $K$ si $P$ s'écrit comme produit de facteurs de degré 1 sur $K$ : $P=a\\prod(X-r_i)$."},
    {id:"def-polynome-irreductible", type:"def", q:"Définir un polynôme irréductible", a:"$P$ non constant est irréductible sur $K$ si ses seuls diviseurs sont les constantes non nulles et les $\\lambda P$ (pas de factorisation non triviale)."},
    {id:"def-fractions-rationnelles-poles", type:"def", q:"Définir fraction rationnelle, fonction rationnelle, pôle", a:"Fraction rationnelle : $F=P/Q$, $P,Q\\in K[X]$, $Q\\ne0$. Pôle de $F$ : racine de $Q$ non simplifiable avec $P$."},
    {id:"formule-binome-polynomes", type:"formule", q:"Formule du binôme de Newton (rappel, cadre polynomial)", a:"$$(X+a)^n = \\sum_{k=0}^n \\binom{n}{k}X^ka^{n-k}$$"},
    {id:"prop-degre-somme-produit", type:"propriété", q:"Degré de la somme et du produit de polynômes", a:"$\\deg(P+Q) \\le \\max(\\deg P,\\deg Q)$ (égalité si $\\deg P\\ne\\deg Q$)&lt;br&gt;$\\deg(PQ) = \\deg P + \\deg Q$"},
    {id:"prop-integrite-K-X", type:"propriété", q:"Intégrité de $K[X]$", a:"$PQ=0 \\Rightarrow P=0$ ou $Q=0$ (pas de diviseurs de zéro)."},
    {id:"prop-division-euclidienne-Z-KX", type:"propriété", q:"Division euclidienne dans $\\mathbb Z$ et $K[X]$ : analogie", a:"Même structure : $A=BQ+R$ avec une condition de \"petitesse\" sur $R$ ($|R|<|B|$ dans $\\mathbb Z$, $\\deg R<\\deg B$ dans $K[X]$)."},
    {id:"prop-factorisation-racine", type:"propriété", q:"Factorisation via une racine", a:"$a$ racine de $P$ $\\iff$ $(X-a)|P$ $\\iff$ $P = (X-a)Q$ pour un certain $Q\\in K[X]$."},
    {id:"prop-racines-coefficients", type:"propriété", q:"Nombre de racines et degré", a:"Un polynôme non nul de degré $n$ a au plus $n$ racines (comptées sans multiplicité, ou $n$ avec multiplicité)."},
    {id:"formule-leibniz-polynome", type:"formule", q:"Formule de Leibniz pour polynômes (rappel)", a:"$$(PQ)^{(n)} = \\sum_{k=0}^n \\binom{n}{k} P^{(k)}Q^{(n-k)}$$"},
    {id:"formule-taylor-polynomial", type:"formule", q:"Formule de Taylor polynomiale", a:"Pour $P$ de degré $n$ : $$P(X) = \\sum_{k=0}^n \\dfrac{P^{(k)}(a)}{k!}(X-a)^k$$"},
    {id:"prop-racine-multiple-derivees", type:"propriété", q:"Lien racine multiple et dérivées successives", a:"$a$ est racine de $P$ d'ordre $\\ge k$ ssi $P(a)=P'(a)=\\cdots=P^{(k-1)}(a)=0$."},
    {id:"prop-somme-produit-racines", type:"propriété", q:"Somme et produit des racines d'un polynôme scindé", a:"Pour $P=a_n\\prod(X-r_i)$ de degré $n$ : $\\sum r_i = -a_{n-1}/a_n$, $\\prod r_i = (-1)^n a_0/a_n$ (relations coefficients-racines)."},
    {id:"thm-alembert-gauss", type:"propriété", q:"Théorème de d'Alembert-Gauss", a:"Tout polynôme non constant de $\\mathbb C[X]$ admet au moins une racine dans $\\mathbb C$ ($\\mathbb C$ est algébriquement clos)."},
    {id:"prop-irreductibles-C-R", type:"propriété", q:"Polynômes irréductibles dans $\\mathbb C[X]$ et $\\mathbb R[X]$", a:"Dans $\\mathbb C[X]$ : irréductibles = degré 1. Dans $\\mathbb R[X]$ : irréductibles = degré 1, ou degré 2 à discriminant strictement négatif."},
    {id:"prop-decomposition-irreductibles", type:"propriété", q:"Décomposition en facteurs irréductibles (existence et unicité)", a:"Tout polynôme non constant se factorise de façon unique (à l'ordre et aux constantes près) en produit de facteurs irréductibles."},
    {id:"prop-caracterisation-divisibilite-C-racines", type:"propriété", q:"Caractérisation de la divisibilité dans $\\mathbb C[X]$ via les racines", a:"$A | B$ dans $\\mathbb C[X]$ ssi toute racine de $A$ est racine de $B$ avec une multiplicité au moins égale."},
    {id:"prop-decomposition-fraction-rationnelle", type:"propriété", q:"Décomposition en éléments simples d'une fraction rationnelle", a:"Toute fraction rationnelle $F=P/Q$ se décompose (partie entière + somme d'éléments simples associés à chaque pôle avec sa multiplicité) : $F = E + \\sum \\dfrac{a_{i,k}}{(X-p_i)^k}$."},
    {id:"methode-calcul-degre", type:"méthode", q:"Méthode : calculer le degré d'un polynôme composé/produit", a:"Utiliser $\\deg(PQ)=\\deg P+\\deg Q$ et $\\deg(P\\circ Q) = \\deg P \\times \\deg Q$ (attention aux cas particuliers : polynôme nul, constantes)."},
    {id:"methode-poser-division-euclidienne", type:"méthode", q:"Méthode : poser une division euclidienne de polynômes", a:"Diviser terme de plus haut degré par terme de plus haut degré du diviseur, soustraire, répéter jusqu'à obtenir un reste de degré strictement inférieur au diviseur."},
    {id:"methode-reste-division-par-X-a", type:"méthode", q:"Calculer le reste de la division de $P$ par $X-a$", a:"Le reste est la constante $P(a)$ (conséquence directe de la division euclidienne, $\\deg R<1$)."},
    {id:"methode-evaluation-polynome", type:"méthode", q:"Méthode : évaluer un polynôme en un point", a:"Substituer directement la valeur dans l'expression, ou utiliser la méthode de Horner pour optimiser le nombre d'opérations."},
    {id:"methode-trouver-racine-factoriser", type:"méthode", q:"Méthode : trouver une racine évidente puis factoriser", a:"Tester les valeurs simples ($0,\\pm1,\\pm2\\ldots$) ou les diviseurs du terme constant (racines rationnelles), puis diviser $P$ par $(X-a)$ pour factoriser."},
    {id:"methode-horner", type:"méthode", q:"Méthode de Horner pour évaluer un polynôme", a:"Réécrire $P(x)=a_0+x(a_1+x(a_2+\\cdots+x\\, a_n))$ : évaluation par imbrications successives, réduit le nombre de multiplications de $O(n^2)$ à $O(n)$."},
    {id:"methode-factorisation-Xn-1", type:"méthode", q:"Factorisation de $X^n-1$ dans $\\mathbb C[X]$", a:"$$X^n - 1 = \\prod_{k=0}^{n-1} (X - e^{2ik\\pi/n})$$ (produit sur toutes les racines $n$-ièmes de l'unité)."}
  ]
});
