/* Cours : Maths — Chapitre 5 : Calcul intégral */
window.OSCILLO_COURSES = window.OSCILLO_COURSES || [];
window.OSCILLO_COURSES.push({
  subject: "maths",
  id: "m5",
  name: "Calcul intégral",
  cards: [
    {id:"propriete-ensemble-primitives", type:"propriété", q:"Énoncer la propriété de l'ensemble des primitives d'une fonction $f$ continue sur $I$ (à partir d'une primitive $P$)", a:"Si $I$ est un intervalle, $f:I\\to\\mathbb{K}$ continue sur $I$, $P:I\\to\\mathbb{K}$ une primitive de $f$ sur $I$, alors $$\\{F \\mid F \\text{ est une primitive de } f \\text{ sur } I\\}=\\{x\\mapsto P(x)+C \\mid C\\in\\mathbb{K}\\}$$ Autrement dit : toute primitive de $f$ sur $I$ est de cette forme ET toute fonction de cette forme est une primitive de $f$ sur $I$."},
    {id:"def-primitive-fonction-complexe", type:"def", q:"Définir une primitive d'une fonction $f:I\\to\\mathbb{C}$ à valeurs complexes", a:"Soient $f_R:x\\mapsto \\text{Re}(f(x))$ et $f_I:x\\mapsto \\text{Im}(f(x))$, $F_R$ et $F_I$ des primitives de $f_R$ et $f_I$ sur $I$, alors $$x\\mapsto F_R(x)+iF_I(x)$$ est une primitive de $f$ sur $I$."},
    {id:"def-integrale-sans-borne", type:"def", q:"Définir la notation « intégrale sans borne » $\\int f$ ou $\\int f(x)\\,dx$", a:"Si $F$ est une primitive de $f$, on note l'ensemble de ses primitives, sans précision de l'ensemble de définition : $$\\int f(x)\\,dx=\\{x\\mapsto F(x)+C \\mid C\\in\\mathbb{R}\\}, \\qquad \\text{ou simplement } \\int f=\\{F+C \\mid C\\in\\mathbb{R}\\}$$"},
    {id:"formule-primitives-usuelles-operations", type:"formule", q:"Primitives associées aux opérations sur les fonctions ($\\alpha u$, $u+v$, $u'v+uv'$, $\\frac{u'v-uv'}{v^2}$, $u'v'(u(x))$)", a:"$$\\int \\alpha u(x)\\,dx = \\alpha U(x)+C \\qquad \\int (u(x)+v(x))\\,dx=U(x)+V(x)+C$$ $$\\int (u'(x)v(x)+u(x)v'(x))\\,dx=u(x)v(x)+C \\qquad \\int \\dfrac{u'(x)v(x)-u(x)v'(x)}{v(x)^2}\\,dx=\\dfrac{u(x)}{v(x)}+C$$ $$\\int u'(x)v'(u(x))\\,dx=(v\\circ u)(x)+C=v(u(x))+C$$"},
    {id:"formule-primitives-usuelles-puissances-ln", type:"formule", q:"Primitives usuelles : $\\alpha$, $x^\\alpha$ ($\\alpha\\neq-1$), $\\frac{1}{x}$ (et composées $u(x)^\\alpha$, $\\frac{u'(x)}{u(x)}$)", a:"$$\\int \\alpha\\,dx=\\alpha x+C \\ \\text{sur } \\mathbb{R} \\qquad \\int x^\\alpha\\,dx=\\dfrac{x^{\\alpha+1}}{\\alpha+1}+C \\ \\text{sur } \\mathbb{R}_+^*,\\ \\alpha\\neq-1$$ $$\\int u'(x)u(x)^\\alpha\\,dx=\\dfrac{u(x)^{\\alpha+1}}{\\alpha+1}+C,\\ \\alpha\\neq-1$$ $$\\int \\dfrac{1}{x}\\,dx=\\ln|x|+C \\ \\text{sur }\\ ]{-\\infty};0[ \\text{ ou } \\mathbb{R}_+^* \\qquad \\int \\dfrac{u'(x)}{u(x)}\\,dx=\\ln|u(x)|+C \\ (u(x)>0 \\text{ ou } u(x)<0)$$"},
    {id:"formule-primitives-usuelles-exponentielle-log", type:"formule", q:"Primitives usuelles : $e^x$, $e^{u(x)}$, $e^{\\lambda x}$, $\\ln x$, $\\ln u(x)$", a:"$$\\int e^x\\,dx=e^x+C \\ \\text{sur } \\mathbb{R} \\qquad \\int u'(x)e^{u(x)}\\,dx=e^{u(x)}+C$$ $$\\int e^{\\lambda x}\\,dx=\\dfrac{e^{\\lambda x}}{\\lambda}+C,\\ C\\in\\mathbb{C},\\ \\lambda\\in\\mathbb{C}^*$$ $$\\int \\ln x\\,dx=x(\\ln x-1)+C \\ \\text{sur } \\mathbb{R} \\qquad \\int u'(x)\\ln(u(x))\\,dx=u(x)(\\ln(u(x))-1)+C$$"},
    {id:"formule-primitives-usuelles-cos-sin", type:"formule", q:"Primitives usuelles de $\\cos$, $\\sin$ (et de leurs composées $u'(x)\\cos u(x)$, $u'(x)\\sin u(x)$)", a:"$$\\int \\cos x\\,dx=\\sin x+C \\ \\text{sur } \\mathbb{R} \\qquad \\int u'(x)\\cos u(x)\\,dx=\\sin u(x)+C$$ $$\\int \\sin x\\,dx=-\\cos x+C \\ \\text{sur } \\mathbb{R} \\qquad \\int u'(x)\\sin u(x)\\,dx=-\\cos u(x)+C$$"},
    {id:"formule-primitives-usuelles-tan-inverse-sin-cos", type:"formule", q:"Primitives usuelles de $\\frac{1}{\\cos^2 x}$, $\\frac{1}{\\sin x}$ et $\\frac{1}{\\cos x}$", a:"$$\\int \\dfrac{1}{\\cos^2 x}\\,dx=\\int(1+\\tan^2x)\\,dx=\\tan x+C \\ \\text{sur } \\left]{-\\dfrac{\\pi}{2}}+k\\pi;\\dfrac{\\pi}{2}+k\\pi\\right[$$ $$\\int \\dfrac{u'(x)}{\\cos^2 u(x)}\\,dx=\\tan u(x)+C$$ $$\\int \\dfrac{1}{\\sin x}\\,dx=\\ln\\left|\\tan\\dfrac{x}{2}\\right|+C \\ \\text{sur } ]k\\pi;(k+1)\\pi[$$ $$\\int \\dfrac{1}{\\cos x}\\,dx=\\ln\\left|\\tan\\left(\\dfrac{x}{2}+\\dfrac{\\pi}{4}\\right)\\right|+C \\ \\text{sur } \\left]{-\\dfrac{\\pi}{2}}+k\\pi;\\dfrac{\\pi}{2}+k\\pi\\right[$$"},
    {id:"formule-primitives-usuelles-arcsin-arccos-arctan", type:"formule", q:"Primitives usuelles de $\\frac{\\pm 1}{\\sqrt{1-x^2}}$, $\\frac{1}{x^2+1}$ et $\\frac{1}{(x+b)^2+a^2}$", a:"$$\\int \\dfrac{\\pm 1}{\\sqrt{1-x^2}}\\,dx=\\text{Arcsin}\\,x \\text{ ou } \\text{Arccos}\\,x + C \\ \\text{sur } ]{-1};1[$$ $$\\int \\dfrac{\\pm u'(x)}{\\sqrt{1-u(x)^2}}\\,dx=\\text{Arcsin}\\,u(x) \\text{ ou } \\text{Arccos}\\,u(x)+C$$ $$\\int \\dfrac{1}{x^2+1}\\,dx=\\text{Arctan}\\,x+C \\ \\text{sur } \\mathbb{R} \\qquad \\int \\dfrac{u'(x)}{u(x)^2+1}\\,dx=\\text{Arctan}\\,u(x)+C$$ $$\\int \\dfrac{1}{(x+b)^2+a^2}\\,dx=\\dfrac{1}{a}\\text{Arctan}\\left(\\dfrac{x+b}{a}\\right)+C \\ (a\\neq0) \\ \\text{sur } \\mathbb{R}$$"},
    {id:"formule-primitives-usuelles-hyperboliques", type:"formule", q:"Primitives usuelles de $\\text{ch}\\,u(x)$, $\\text{sh}\\,u(x)$ et $\\frac{1}{\\text{ch}^2u(x)}$", a:"$$\\int u'(x)\\,\\text{ch}\\,u(x)\\,dx=\\text{sh}\\,u(x)+C \\qquad \\int u'(x)\\,\\text{sh}\\,u(x)\\,dx=\\text{ch}\\,u(x)+C$$ $$\\int \\dfrac{u'(x)}{\\text{ch}^2u(x)}\\,dx=\\text{th}\\,u(x)+C$$"},
    {id:"propriete-lien-primitive-integrale", type:"propriété", q:"Lien entre primitive et intégrale sur $[a,b]$", a:"Soient $[a,b]$ un intervalle, $f$ une fonction intégrable sur $[a,b]$ et $F$ une primitive de $f$ sur $[a,b]$, alors $$\\int_a^b f=[F(x)]_{x=a}^{x=b}=F(b)-F(a)$$"},
    {id:"propriete-lien-integrale-primitive", type:"propriété", q:"Lien entre intégrale et primitive : quelle est la fonction $x\\mapsto\\int_c^x f$ ?", a:"Soient $[a,b]$ un intervalle, $f$ une fonction intégrable sur $[a,b]$ et $c\\in[a,b]$, alors $$\\begin{array}{rcl}[a,b]&\\to&\\mathbb{R}\\\\ x&\\mapsto&\\displaystyle\\int_c^x f\\end{array}$$ est la primitive de $f$ qui s'annule en $c$."},
    {id:"propriete-rappels-calcul-integral", type:"propriété", q:"Rappeler les propriétés de base du calcul intégral (renversement des bornes, constante, dérivée, linéarité, variable muette)", a:"Pour $[a,b]$ un intervalle, $\\lambda\\in\\mathbb{R}$, $f,g$ intégrables sur $[a,b]$, $u$ dérivable sur $[a,b]$ : $$\\int_a^b f=-\\int_b^a f \\qquad \\int_a^b \\lambda=\\lambda(b-a) \\qquad \\int_a^b u'=u(b)-u(a)$$ $$\\int_a^b (f+g)=\\int_a^b f+\\int_a^b g \\qquad \\int_a^b \\lambda f=\\lambda \\int_a^b f$$ $$\\int_a^b f=\\int_a^b f(x)\\,dx=\\int_a^b f(t)\\,dt=\\int_a^b f(y)\\,dy \\quad \\text{(la variable d'intégration est muette)}$$"},
    {id:"propriete-relation-chasles", type:"propriété", q:"Énoncer la relation de Chasles pour les intégrales", a:"Soient $[a,b]$ un intervalle, $c\\in[a,b]$, $f$ une fonction intégrable sur $[a,b]$, alors $$\\int_a^b f=\\int_a^c f+\\int_c^b f$$"},
    {id:"def-fonction-classe-c1", type:"def", q:"Définir une fonction de classe $\\mathcal{C}^1$ sur un intervalle $I$", a:"Soient $I,J$ deux sous-ensembles de $\\mathbb{R}$ et $u:I\\to J$. On dit que $u$ est de classe $\\mathcal{C}^1$ sur $I$ si $u$ est continue et dérivable sur $I$ et que sa fonction dérivée $u'$ est également continue sur $I$."},
    {id:"theoreme-integration-par-parties", type:"propriété", q:"Énoncer le théorème d'intégration par parties (IPP)", a:"Soient $u$ et $v$ deux fonctions de classe $\\mathcal{C}^1$ sur un intervalle $[a,b]$, alors $$\\int_a^b u(x)v'(x)\\,dx=[u(x)v(x)]_{x=a}^{x=b}-\\int_a^b u'(x)v(x)\\,dx$$ Preuve : $uv$ est de classe $\\mathcal{C}^1$ (produit de fonctions $\\mathcal{C}^1$), donc $(uv)'=u'v+uv'$ est continue et on intègre cette égalité entre $a$ et $b$ en utilisant le lien primitive-intégrale."},
    {id:"theoreme-changement-de-variable", type:"propriété", q:"Énoncer le théorème du changement de variable (version générale)", a:"Soient $\\alpha<\\beta$ et $f:[\\alpha,\\beta]\\to\\mathbb{R}$ continue. On considère $\\varphi:I\\to\\mathbb{R}$ (avec $I=[a,b]$ ou $[b,a]$) telle que $\\varphi$ soit de classe $\\mathcal{C}^1$ sur $I$, $\\varphi(a)=\\alpha$, $\\varphi(b)=\\beta$, et $f$ continue sur $\\varphi(I)$, alors $$\\int_\\alpha^\\beta f(x)\\,dx=\\int_a^b f(\\varphi(t))\\varphi'(t)\\,dt$$ (on retient : $x=\\varphi(t)$, $dx=\\varphi'(t)\\,dt$)"},
    {id:"corollaire-changement-variable-bijectif", type:"propriété", q:"Énoncer le corollaire du changement de variable utilisé en pratique (cas où $\\varphi$ est bijective)", a:"Soient $\\alpha<\\beta$ et $f:[\\alpha,\\beta]\\to\\mathbb{R}$. On considère $\\varphi:I\\to\\mathbb{R}$ telle que $\\varphi$ soit de classe $\\mathcal{C}^1$ sur $I$ et bijective de $I$ dans $[\\alpha,\\beta]$, $a=\\varphi^{-1}(\\alpha)$, $b=\\varphi^{-1}(\\beta)$, et $f$ continue sur $[\\alpha,\\beta]$, alors $$\\int_\\alpha^\\beta f(x)\\,dx=\\int_{\\varphi^{-1}(\\alpha)}^{\\varphi^{-1}(\\beta)} f(\\varphi(t))\\varphi'(t)\\,dt$$"},
    {id:"propriete-intervalle-centre-parite", type:"propriété", q:"Énoncer la propriété liant intégrale sur un intervalle centré et parité de $f$", a:"Soient $a\\in\\mathbb{R}_+$ et $f$ continue sur $]{-a};a[$, alors : si $f$ est paire, $$\\int_{-a}^a f=2\\int_0^a f$$ si $f$ est impaire, $$\\int_{-a}^a f=0$$ Preuve : par Chasles $\\int_{-a}^a f=\\int_{-a}^0 f+\\int_0^a f$, puis changement de variable $x=\\varphi(t)=-t$ sur $\\int_{-a}^0 f$."},
    {id:"methode-ipp-polynome-autre", type:"méthode", q:"Méthode d'IPP quand on a un produit polynôme × autre fonction", a:"Il faut toujours choisir la fonction polynomiale comme fonction à dériver, car si on choisit de la primitiver, on augmente le degré de la partie polynomiale et on risque d'intégrer par parties éternellement."},
    {id:"methode-ipp-exponentielle-trigonometrique", type:"méthode", q:"Méthode d'IPP pour un produit exponentielle × trigonométrique", a:"On peut choisir de primitiver la partie exponentielle ou la partie trigonométrique, mais si on applique une seconde intégration par parties, il faut faire le même choix pour éviter de revenir à l'intégrale de départ."},
    {id:"methode-primitive-c-sur-a-plus-bx-carre", type:"méthode", q:"Méthode pour trouver une primitive de $x\\mapsto \\dfrac{C}{A+Bx^2}$ (avec $A,B\\in\\mathbb{R}_+^*$)", a:"On se ramène successivement à chercher une primitive de : $\\dfrac{1}{A+Bx^2}$ (facteur $C$ mis de côté), puis $\\dfrac{1}{1+Dx^2}$ avec $D=B/A$ (facteur $1/A$ mis de côté), puis $\\dfrac{1}{1+(\\alpha x)^2}$ avec $\\alpha=\\sqrt{D}$, puis on reconnaît $\\dfrac{(\\alpha x)'}{1+(\\alpha x)^2}$ (facteur $1/\\alpha$ mis de côté), dont une primitive est $\\text{Arctan}(\\alpha x)$."},
    {id:"methode-forme-canonique-trinome", type:"méthode", q:"Méthode de mise sous forme canonique de $ax^2+bx+c$ ($a\\neq0$)", a:"$$ax^2+bx+c=a\\left(x^2+\\dfrac{b}{a}x+\\dfrac{c}{a}\\right)=a\\left[\\left(x+\\dfrac{b}{2a}\\right)^2+\\dfrac{4ac-b^2}{4a^2}\\right]$$ (en posant $B=b/a$, $C=c/a$, puis en complétant le carré $x^2+2\\cdot\\frac{B}{2}x+C=(x+\\frac{B}{2})^2+C-(\\frac{B}{2})^2$). Si $b^2-4ac<0$ (donc $4ac-b^2>0$), on obtient la forme canonique."},
    {id:"methode-primitives-p-sur-trinome", type:"méthode", q:"Méthode pour trouver une primitive de $x\\mapsto \\dfrac{P(x)}{ax^2+bx+c}$ ($P$ polynôme, $a\\neq0$)", a:"1. Si $\\deg(P)\\geq2$ : division euclidienne $P=(ax^2+bx+c)Q+R$ avec $\\deg(R)<2$, on écrit $\\frac{P}{ax^2+bx+c}=Q+\\frac{R}{ax^2+bx+c}$ (cas suivants avec $R$ au lieu de $P$).<br>2. Si $\\deg(P)=1$ : on fait apparaître $(ax^2+bx+c)'$ au numérateur pour obtenir une primitive standard $\\ln|ax^2+bx+c|$, plus un terme constant $\\times \\frac{1}{ax^2+bx+c}$ (cas 3 suivant).<br>3. Si $P=1$ : selon le signe de $\\Delta=b^2-4ac$ — si $\\Delta=0$ : $\\frac{1}{a(x-r)^2}$ (primitive standard) ; si $\\Delta>0$ : décomposition en éléments simples $\\frac{1}{a}\\left(\\frac{A}{x-r_1}+\\frac{B}{x-r_2}\\right)$ ; si $\\Delta<0$ : mise sous forme canonique puis primitive en Arctan."},
    {id:"remarque-inversion-limite-integrale", type:"propriété", q:"Peut-on toujours intervertir une limite et une intégrale ? (contre-exemples avec $f_n$)", a:"Non, on ne peut en général pas inverser une limite et une intégrale, même si les fonctions $f_n$ tendent vers la fonction nulle quand $n\\to+\\infty$. Contre-exemples avec des « bosses » de plus en plus fines sur $[0,1]$ : $\\int_{[0,1]}f_n=1/n\\to0$ ; $\\int_{[0,1]}f_n=1\\to1$ ; $\\int_{[0,1]}f_n=n\\to+\\infty$. Pourtant l'aire sous la courbe peut tendre vers des valeurs différentes selon la forme des $f_n$."},
  ]
});
