/* Cours : Mathématiques — Ch.17 : Algèbre linéaire II - dimension des espaces vectoriels */
window.OSCILLO_COURSES = window.OSCILLO_COURSES || [];
window.OSCILLO_COURSES.push({
  subject: "maths",
  id: "m17",
  name: "Algèbre linéaire II : dimension des espaces vectoriels",
  cards: [
    {id:"def-vect-famille-generatrice", type:"def", q:"Définir Vect et famille génératrice", a:"$\\mathrm{Vect}(u_1,\\dots,u_n)$ : ensemble des combinaisons linéaires des $u_i$. La famille $(u_1,\\dots,u_n)$ est génératrice de $E$ si $\\mathrm{Vect}(u_1,\\dots,u_n)=E$."},
    {id:"def-dimension-finie", type:"def", q:"Définir un ev de dimension finie", a:"$E$ est de dimension finie s'il admet une famille génératrice finie."},
    {id:"def-famille-libre-liee", type:"def", q:"Définir famille libre, liée, vecteurs linéairement (in)dépendants", a:"$(u_1,\\dots,u_n)$ libre si $\\sum \\lambda_i u_i = 0 \\Rightarrow \\lambda_1=\\cdots=\\lambda_n=0$ (seule la combinaison triviale donne 0). Liée sinon (dépendante)."},
    {id:"def-famille-polynomes-echelonnee", type:"def", q:"Définir une famille de polynômes échelonnée en degré", a:"Famille $(P_1,\\dots,P_n)$ dont les degrés sont tous distincts (souvent rangés en ordre strictement croissant) : garantit automatiquement la liberté de la famille."},
    {id:"def-base-coordonnees", type:"def", q:"Définir base et coordonnées", a:"Base : famille à la fois libre et génératrice. Coordonnées d'un vecteur $x$ dans la base $(e_1,\\dots,e_n)$ : uniques scalaires $x_i$ tels que $x=\\sum x_ie_i$."},
    {id:"def-bases-canoniques", type:"def", q:"Définir les bases canoniques de $K^n$, $K_n[X]$, $\\mathcal M_{n,p}(K)$", a:"$K^n$ : $((1,0,\\dots,0),\\dots,(0,\\dots,0,1))$. $K_n[X]$ : $(1,X,X^2,\\dots,X^n)$. $\\mathcal M_{n,p}(K)$ : matrices élémentaires $E_{ij}$ (1 en position $(i,j)$, 0 ailleurs)."},
    {id:"def-dimension-ev", type:"def", q:"Définir la dimension d'un ev", a:"$\\dim E$ = nombre d'éléments de n'importe quelle base de $E$ (cardinal commun à toutes les bases, cf. théorème d'invariance)."},
    {id:"def-egalite-ev", type:"def", q:"Rappel : égalité de deux ev de dimension finie", a:"Si $F\\subset E$ avec $\\dim F = \\dim E$ (dimensions finies égales), alors $F=E$."},
    {id:"def-rang-famille", type:"def", q:"Définir le rang d'une famille de vecteurs", a:"$\\mathrm{rg}(u_1,\\dots,u_n) = \\dim \\mathrm{Vect}(u_1,\\dots,u_n)$."},
    {id:"def-hyperplan", type:"def", q:"Définir un hyperplan", a:"Sev de $E$ (dimension finie $n$) de dimension $n-1$. Équivalent : noyau d'une forme linéaire non nulle."},
    {id:"prop-sous-ev-dimension-finie", type:"propriété", q:"Tout sev d'un ev de dimension finie est de dimension finie", a:"Si $E$ dimension finie et $F$ sev de $E$, alors $F$ est aussi de dimension finie, avec $\\dim F \\le \\dim E$."},
    {id:"prop-simplification-famille-generatrice", type:"propriété", q:"Simplification de l'expression du ev engendré par une famille", a:"On peut retirer d'une famille génératrice tout vecteur qui est combinaison linéaire des autres, sans changer le $\\mathrm{Vect}$."},
    {id:"prop-sur-famille-generatrice", type:"propriété", q:"Sur-famille d'une famille génératrice", a:"Toute sur-famille (ajout de vecteurs) d'une famille génératrice reste génératrice."},
    {id:"prop-r-x-echelonnee-libre", type:"propriété", q:"Famille échelonnée en degré $\\Rightarrow$ libre", a:"Toute famille de polynômes non nuls de degrés deux à deux distincts est libre (les degrés ne peuvent pas se compenser dans une combinaison linéaire nulle)."},
    {id:"prop-vecteur-nul-liee", type:"propriété", q:"Vecteur nul dans une famille $\\Rightarrow$ liée", a:"Toute famille contenant le vecteur nul est automatiquement liée."},
    {id:"prop-sous-famille-libre", type:"propriété", q:"Sous-famille d'une famille libre", a:"Toute sous-famille d'une famille libre est encore libre."},
    {id:"prop-famille-liee-combinaison", type:"propriété", q:"Famille liée et combinaison linéaire", a:"$(u_1,\\dots,u_n)$ liée ssi l'un des $u_i$ est combinaison linéaire des autres."},
    {id:"prop-unicite-decomposition-libre", type:"propriété", q:"Unicité de la décomposition sur une famille libre", a:"Si $(u_i)$ est libre, tout vecteur de $\\mathrm{Vect}(u_i)$ s'écrit de façon unique comme combinaison linéaire des $u_i$."},
    {id:"prop-decomposition-libre-generatrice", type:"propriété", q:"Décomposition unique $\\iff$ libre et génératrice", a:"Une famille est une base ssi tout vecteur de $E$ s'écrit de manière unique comme combinaison linéaire de cette famille."},
    {id:"prop-existence-base-dim-finie", type:"propriété", q:"Existence d'une base en dimension finie", a:"Tout ev de dimension finie non réduit à $\\{0\\}$ admet au moins une base."},
    {id:"thm-base-extraite-incomplete", type:"propriété", q:"Théorème de la base extraite / de la base incomplète", a:"De toute famille génératrice finie, on peut extraire une base. Toute famille libre peut être complétée en une base (en ajoutant des vecteurs, éventuellement pris dans une famille génératrice donnée)."},
    {id:"prop-egalite-cardinal-bases", type:"propriété", q:"Théorème d'invariance de la dimension", a:"Toutes les bases d'un même ev de dimension finie ont le même cardinal (nombre d'éléments)."},
    {id:"prop-nombre-elements-famille-generatrice-libre", type:"propriété", q:"Comparaison cardinal famille libre / famille génératrice", a:"Dans un ev de dimension $n$ : toute famille libre a au plus $n$ éléments, toute famille génératrice a au moins $n$ éléments."},
    {id:"prop-image-base-application-lineaire", type:"propriété", q:"Image d'une base par une application linéaire", a:"Une application linéaire est entièrement déterminée par les images des vecteurs d'une base de l'espace de départ."},
    {id:"prop-lien-surjection-injection-image-base", type:"propriété", q:"Lien surjection/injection et image d'une base", a:"Si $(e_i)$ base de $E$ : $u$ surjective ssi $(u(e_i))$ génératrice de $F$. $u$ injective ssi $(u(e_i))$ libre dans $F$. $u$ bijective ssi $(u(e_i))$ base de $F$."},
    {id:"prop-caracterisation-dim-egales-injective-surjective", type:"propriété", q:"En dimension finie égale : équivalence injective/surjective/bijective", a:"Si $\\dim E = \\dim F$ (finies) et $u:E\\to F$ linéaire : $u$ injective $\\iff$ $u$ surjective $\\iff$ $u$ bijective."},
    {id:"prop-sev-dimensions-egales", type:"propriété", q:"Sev et dimensions", a:"Si $F$ sev de $E$ (dim finie) : $\\dim F \\le \\dim E$, avec égalité ssi $F=E$."},
    {id:"prop-existence-sev-supplementaire", type:"propriété", q:"Existence de supplémentaire (dimension finie)", a:"Tout sev $F$ d'un ev $E$ de dimension finie admet au moins un supplémentaire dans $E$ (non unique en général)."},
    {id:"prop-caracterisation-sev-supplementaires-dim", type:"propriété", q:"Caractérisation des supplémentaires via dimension", a:"Si $F\\cap G=\\{0\\}$ et $\\dim F+\\dim G = \\dim E$, alors $E=F\\oplus G$ (une seule condition à vérifier en plus de la dimension)."},
    {id:"formule-grassmann", type:"formule", q:"Formule de Grassmann", a:"$$\\dim(F+G) = \\dim F + \\dim G - \\dim(F\\cap G)$$"},
    {id:"thm-rang", type:"propriété", q:"Théorème du rang", a:"Pour $u:E\\to F$ linéaire, $E$ de dimension finie : $$\\dim E = \\dim(\\ker u) + \\mathrm{rg}(u), \\quad \\text{où } \\mathrm{rg}(u)=\\dim(\\mathrm{Im}\\,u)$$"},
    {id:"prop-caracterisations-bijection-dim-finie", type:"propriété", q:"Caractérisations de la bijectivité en dimension finie (via rang/noyau)", a:"$u$ bijective $\\iff \\ker u=\\{0\\}$ et $\\mathrm{rg}(u)=\\dim F$ $\\iff$ (si $\\dim E=\\dim F$) une seule des deux conditions suffit."},
    {id:"prop-rang-composee", type:"propriété", q:"Rang d'une composée d'applications linéaires", a:"$\\mathrm{rg}(v\\circ u) \\le \\min(\\mathrm{rg}\\,u, \\mathrm{rg}\\,v)$"},
    {id:"prop-invariance-rang-isomorphisme", type:"propriété", q:"Invariance du rang par composition avec un isomorphisme", a:"Si $v$ isomorphisme, $\\mathrm{rg}(v\\circ u) = \\mathrm{rg}(u\\circ v) = \\mathrm{rg}(u)$ (composer par une bijection ne change pas le rang)."},
    {id:"prop-dimension-hyperplan", type:"propriété", q:"Dimension d'un hyperplan", a:"Un hyperplan de $E$ (dim $n$) a pour dimension $n-1$ ; c'est le noyau d'une forme linéaire non nulle."},
    {id:"prop-supplementaire-hyperplan", type:"propriété", q:"Supplémentaire d'un hyperplan", a:"Tout supplémentaire d'un hyperplan $H$ est une droite vectorielle (dimension 1), engendrée par un vecteur $u\\notin H$."},
    {id:"methode-calcul-rang", type:"méthode", q:"Méthode : calculer le rang d'une famille de vecteurs", a:"Échelonner la famille par opérations élémentaires (combinaisons linéaires, sans changer le Vect), le rang est le nombre de vecteurs non nuls restants (indépendants) à la fin."},
    {id:"methode-recherche-base", type:"méthode", q:"Méthode : rechercher une base d'un sev", a:"Si $F=\\mathrm{Vect}(\\text{famille})$ : extraire une famille libre maximale (base extraite). Si $F=\\ker u$ ou $F$ défini par équations : paramétrer les solutions et identifier les vecteurs générateurs indépendants."}
  ]
});
