/* Cours : Physique — EL3 : Électronique non-linéaire */
window.OSCILLO_COURSES = window.OSCILLO_COURSES || [];
window.OSCILLO_COURSES.push({
  subject: "physique",
  id: "el3",
  name: "Électronique non-linéaire",
  year: "spe",
  cards: [
    {id:"def-systeme-non-lineaire", type:"def", q:"Définition d'un système non-linéaire", a:"Système qui ne vérifie pas le principe de superposition : la réponse à une somme d'entrées n'est pas la somme des réponses. La relation entrée-sortie n'est pas linéaire."},
    {id:"def-deux-types-non-linearites", type:"def", q:"Deux types de non-linéarités, avec un exemple pour chacun", a:"Non-linéarité de seuil : la réponse ne démarre qu'au-delà d'un seuil (ex : diode, tension de seuil $V_{seuil}$).<br>Non-linéarité de saturation : la réponse est bornée au-delà d'une certaine valeur d'entrée (ex : ALI saturé)."},
    {id:"propriete-systeme-non-lineaire", type:"propriété", q:"Propriétés d'un système non linéaire", a:"Pas de principe de superposition ; génération d'harmoniques (un signal sinusoïdal en entrée produit un signal non sinusoïdal en sortie, contenant des harmoniques de la fréquence fondamentale) ; comportement pouvant dépendre de l'amplitude du signal."},
    {id:"methode-algorithme-etude-non-lineaire", type:"méthode", q:"Algorithme d'étude d'un système non-linéaire", a:"1) Formuler une hypothèse sur l'état du composant non-linéaire (diode passante/bloquée, ALI linéaire/saturé).<br>2) Résoudre le circuit sous cette hypothèse (calcul linéaire).<br>3) Vérifier la cohérence de l'hypothèse avec le résultat (signe du courant pour une diode, valeur de $V_s$ par rapport à $V_{sat}$ pour un ALI).<br>4) Si incohérent, reprendre avec l'hypothèse opposée ; répéter pour chaque intervalle où l'état change."},
    {id:"def-diode-symbole-caracteristique", type:"def", q:"Symbole de la diode et allure qualitative de sa caractéristique", a:"Symbole : triangle (anode) pointant vers une barre (cathode), le courant conventionnel passe de l'anode vers la cathode en sens direct.<br>Caractéristique $i(u)$ : quasi nulle pour $u<V_{seuil}$ (≈0,6-0,7V pour le silicium), puis croissance rapide (quasi-verticale) au-delà."},
    {id:"propriete-shockley-coherence", type:"propriété", q:"Cohérence entre l'équation de Shockley et la caractéristique tracée de la diode", a:"Pour $u\\ll0$ (polarisation inverse), $i\\to-I_0$ (courant de saturation inverse, très faible) : la diode est bloquée.<br>Pour $u>0$ suffisamment grand, l'exponentielle domine et $i$ croît très rapidement (courbe quasi-verticale) : cela correspond bien à un seuil apparent puis une forte pente."},
    {id:"propriete-shockley-sens-physique", type:"propriété", q:"Sens physique de l'équation de Shockley", a:"Le courant croît exponentiellement avec la tension directe car il traduit le franchissement thermiquement activé d'une barrière de potentiel à la jonction P-N ; le facteur $kT/q$ fixe l'échelle de tension caractéristique (≈26mV à 300K), et $I_0$ dépend de la géométrie/dopage de la diode."},
    {id:"def-diode-ideale-caracteristique", type:"def", q:"Caractéristique de la diode idéale", a:"Deux segments : $i=0$ pour $u<0$ (diode bloquée, interrupteur ouvert) et $u=0$ pour $i>0$ (diode passante, interrupteur fermé / fil), sans tension de seuil ni résistance dynamique."},
    {id:"def-diode-ideale-etats", type:"def", q:"Les deux états de la diode idéale", a:"Bloquée (interrupteur ouvert) : $i=0$, $u\\leq0$.<br>Passante (interrupteur fermé, fil) : $u=0$, $i\\geq0$."},
    {id:"methode-protocole-diode-ideale", type:"méthode", q:"Protocole d'étude de la diode idéale", a:"On formule une hypothèse (passante ou bloquée), on résout le circuit avec le modèle correspondant (fil ou interrupteur ouvert), puis on vérifie la cohérence : si passante, $i$ doit être positif ; si bloquée, $u$ doit être négatif (ou nul). Sinon, on reprend avec l'autre hypothèse."},
    {id:"exemple-redresseur-monoalternance", type:"exemple", q:"Circuit redresseur monoalternance (diode idéale) : tension aux bornes de R et de D pour e(t) sinusoïdal", a:"Pour $e(t)>0$ : diode passante ($u_D=0$), $u_R=e(t)$.<br>Pour $e(t)<0$ : diode bloquée ($i=0$), $u_R=0$ et $u_D=e(t)$.<br>Résultat : $u_R$ ne conserve que les alternances positives de $e(t)$ (signal redressé, coupé pour les valeurs négatives)."},
    {id:"methode-reconnaissance-ali-sature", type:"méthode", q:"Comment reconnaître rapidement le fonctionnement saturé d'un ALI dans un montage ? Cas de doute", a:"Reconnaissance rapide : absence de rétroaction, ou rétroaction uniquement sur l'entrée non-inverseuse (+) → indice fort de saturation.<br>En cas de doute (rétroactions multiples), on lève le doute par le calcul : hypothèse linéaire, calcul de $V_s$, vérification $|V_s|\\leq V_{sat}$ (sinon l'ALI est réellement saturé)."},
    {id:"methode-comparateur-simple", type:"méthode", q:"Montage et relation entrée-sortie du comparateur simple", a:"Montage : pas de rétroaction, $e$ appliqué sur une entrée, l'autre reliée à une référence (ex. masse). L'ALI fonctionne toujours en saturation : $$u_s=+V_{sat}\\text{ si }\\varepsilon>0,\\quad u_s=-V_{sat}\\text{ si }\\varepsilon<0$$ (bascule brutale au passage de $e$ par la référence)."},
    {id:"methode-comparateur-hysteresis-non-inverseur", type:"méthode", q:"Montage et relation entrée-sortie du comparateur à hystérésis non-inverseur", a:"Montage : $e$ sur l'entrée +, rétroaction positive de la sortie vers l'entrée + via un pont diviseur $(R_1,R_2)$, entrée − à la masse.<br>Les seuils de basculement dépendent de l'état précédent de la sortie : bascule à $e=\\pm\\dfrac{R_1}{R_2}V_{sat}$ selon le sens de variation de $e$ (cycle d'hystérésis symétrique autour de 0)."},
    {id:"methode-comparateur-hysteresis-inverseur", type:"méthode", q:"Montage et relation entrée-sortie du comparateur à hystérésis inverseur", a:"Montage : $e$ sur l'entrée −, rétroaction positive de la sortie vers l'entrée + via un pont diviseur, entrée − reçoit $e$.<br>La sortie bascule entre $\\pm V_{sat}$ avec deux seuils différents selon le sens de variation de $e$ (cycle d'hystérésis), et évolue en sens opposé à $e$ (contrairement au non-inverseur)."},
    {id:"def-multiplieur-schema", type:"def", q:"Schéma et relation entrée-sortie du multiplieur", a:"Composant à 2 entrées $e_1,e_2$ et 1 sortie, tel que $$s=k\\,e_1\\,e_2$$ où $k$ est une constante caractéristique du composant (homogène à l'inverse d'une tension, souvent $k=0{,}1\\,V^{-1}$)."},
    {id:"exemple-ad633", type:"exemple", q:"AD633 : exprimer la sortie en fonction des entrées — est-ce un simple multiplieur ?", a:"D'après la notice, l'AD633 réalise $$s=\\dfrac{(X_1-X_2)(Y_1-Y_2)}{10\\,V}+Z$$ Ce n'est pas un simple multiplieur : il calcule le produit de différences de tensions (entrées différentielles) normalisé, avec une entrée $Z$ additionnelle permettant de décaler ou sommer un signal en sortie."},
    {id:"formule-multiplieur-harmoniques", type:"formule", q:"Multiplieur avec e1(t)=E1cos(2πf1t) et e2(t)=E2cos(2πf2t) : expression de la sortie et spectre", a:"$$s(t)=kE_1E_2\\cos(2\\pi f_1t)\\cos(2\\pi f_2t)=\\dfrac{kE_1E_2}{2}\\left[\\cos(2\\pi(f_1+f_2)t)+\\cos(2\\pi(f_1-f_2)t)\\right]$$ Spectre : deux raies, aux fréquences $f_1+f_2$ et $|f_1-f_2|$ (le multiplieur transpose le spectre, ne conserve pas les fréquences d'origine)."},
    {id:"propriete-multiplieur-harmoniques-generation", type:"propriété", q:"Associer le caractère non-linéaire d'un système et la génération d'harmoniques (cas sinusoïdal)", a:"Un système non-linéaire, excité par un signal sinusoïdal, produit en sortie un signal périodique non sinusoïdal, dont la décomposition en série de Fourier contient des harmoniques (fréquences multiples de la fondamentale) — contrairement à un système linéaire qui conserve la même fréquence."},
    {id:"def-hysteresis-memoire", type:"def", q:"Décrire le phénomène d'hystérésis en relation avec la notion de fonction mémoire", a:"Le cycle d'hystérésis signifie que la sortie à un instant donné ne dépend pas seulement de la valeur actuelle de l'entrée, mais aussi de l'historique (de l'état précédent de la sortie) : le système « se souvient » de son dernier état, d'où le terme de fonction mémoire (bistable)."}
  ]
});
