/* Cours : Physique — M3 : Aspects énergétiques du mouvement */
window.OSCILLO_COURSES = window.OSCILLO_COURSES || [];
window.OSCILLO_COURSES.push({
  subject: "physique",
  id: "m3",
  name: "Aspects énergétiques du mouvement",
  cards: [
    {id:"formule-energie-cinetique", type:"formule", q:"Énergie cinétique d'un point matériel", a:"$$E_c=\\dfrac12 mv^2$$"},
    {id:"formule-puissance-force", type:"formule", q:"Puissance d'une force", a:"$$\\mathcal{P}(\\vec{F})=\\vec{F}\\cdot\\vec{v}$$"},
    {id:"formule-theoreme-puissance-cinetique", type:"formule", q:"Énoncer le théorème de la puissance cinétique", a:"Dans un référentiel galiléen, la dérivée temporelle de l'énergie cinétique d'un point matériel est égale à la somme des puissances des forces extérieures : $$\\dfrac{dE_c}{dt}=\\sum\\mathcal{P}(\\vec{F}_{ext})$$"},
    {id:"formule-travail-force", type:"formule", q:"Travail d'une force le long d'un trajet $\\Gamma_{AB}$", a:"$$W_{A\\to B}(\\vec{F})=\\int_{t_A}^{t_B}\\mathcal{P}(\\vec{F})\\,dt=\\int_A^B \\vec{F}\\cdot d\\overrightarrow{OM}=\\int_A^B \\delta W$$"},
    {id:"formule-theoreme-energie-cinetique", type:"formule", q:"Énoncer le théorème de l'énergie cinétique", a:"La variation d'énergie cinétique d'un point matériel entre $A$ et $B$ est égale à la somme des travaux des forces extérieures sur $\\Gamma_{AB}$ : $$\\Delta_{A\\to B}E_c=\\sum W_{A\\to B}(\\vec{F}_{ext})$$"},
    {id:"def-force-conservative", type:"def", q:"Définir une force conservative et son énergie potentielle associée", a:"Force dont le travail entre deux points ne dépend pas du trajet suivi. Une force conservative $\\vec{F}$ dérive d'une énergie potentielle $E_p$ vérifiant $\\delta W(\\vec{F})=-dE_p$, d'où : $$W_{A\\to B}(\\vec{F})=-\\Delta_{A\\to B}E_p$$"},
    {id:"formule-gradient", type:"formule", q:"Expression du gradient d'un champ scalaire en coordonnées cartésiennes, et lien avec une force conservative", a:"$$\\overrightarrow{\\text{grad}}(E_p)=\\dfrac{\\partial E_p}{\\partial x}\\vec{u_x}+\\dfrac{\\partial E_p}{\\partial y}\\vec{u_y}+\\dfrac{\\partial E_p}{\\partial z}\\vec{u_z}$$ Une force conservative s'écrit $$\\vec{F}=-\\overrightarrow{\\text{grad}}(E_p)$$ ($E_p$ définie à une constante près)."},
    {id:"methode-determiner-energie-potentielle", type:"méthode", q:"Méthode : montrer qu'une force est conservative et déterminer son énergie potentielle", a:"Trois façons possibles :<br>1. Montrer que $\\vec{F}=-\\overrightarrow{\\text{grad}}(E_p)$.<br>2. Montrer que le travail sur un trajet $\\Gamma_{AB}$ s'exprime comme une variation d'énergie potentielle : $W_{A\\to B}(\\vec{F})=-\\Delta_{A\\to B}E_p$.<br>3. Montrer que le travail élémentaire s'exprime comme une différentielle : $\\delta W(\\vec{F})=-dE_p$."},
    {id:"formule-energies-potentielles-usuelles", type:"formule", q:"Énergies potentielles usuelles : poids, ressort, gravitation, Coulomb", a:"Poids (axe vertical ascendant) : $E_p=mgz+\\text{cste}$.<br>Ressort : $E_p=\\dfrac12 k(l-l_0)^2+\\text{cste}$.<br>Gravitation : $E_p=-G\\dfrac{m_Am_B}{r}+\\text{cste}$.<br>Coulomb : $E_p=\\dfrac{1}{4\\pi\\varepsilon_0}\\dfrac{q_Aq_B}{r}+\\text{cste}$."},
    {id:"def-energie-mecanique", type:"def", q:"Définir l'énergie mécanique et énoncer le théorème de l'énergie mécanique", a:"$$E_m(M)=E_c(M)+E_p(M)$$ Théorème : $$\\dfrac{dE_m}{dt}=\\sum\\mathcal{P}(\\vec{F}_{ext,NC}), \\qquad \\Delta_{A\\to B}E_m=\\sum W_{A\\to B}(\\vec{F}_{ext,NC})$$ (seules les forces non conservatives font varier $E_m$)."},
    {id:"def-systeme-conservatif", type:"def", q:"Définir un système conservatif", a:"Système dont l'énergie mécanique est conservée au cours du mouvement ⇔ aucune force non conservative ne travaille sur le système."},
    {id:"def-mouvement-unidimensionnel", type:"def", q:"Définir un mouvement unidimensionnel et la condition sur $E_p$ pour qu'il soit accessible", a:"Mouvement décrit par une seule variable de position. Comme $E_m=E_p+\\dfrac12 mv^2\\ge E_p$, le système est astreint à se déplacer uniquement dans les zones où $E_p(x)\\le E_m$."},
    {id:"def-positions-equilibre", type:"def", q:"Définir une position d'équilibre et sa stabilité pour un système conservatif", a:"Position où vitesse et accélération sont nulles ⇔ résultante des forces nulle. Pour un système conservatif : $$\\left.\\dfrac{dE_p}{dx}\\right|_{x=x_{eq}}=0$$ Équilibre stable si $\\left.\\dfrac{d^2E_p}{dx^2}\\right|_{x_{eq}}>0$ ($E_p$ minimale).<br>Équilibre instable si $\\left.\\dfrac{d^2E_p}{dx^2}\\right|_{x_{eq}}<0$ ($E_p$ maximale)."},
    {id:"formule-approximation-harmonique", type:"formule", q:"Approximation harmonique de $E_p$ au voisinage d'un équilibre stable", a:"$$E_p(x)=E_p(x_{eq})+\\left.\\dfrac{d^2E_p}{dx^2}\\right|_{x_{eq}}\\dfrac{(x-x_{eq})^2}{2}+\\dots$$ ⇒ puits de potentiel harmonique (oscillateur harmonique au voisinage de l'équilibre)."}
  ]
});
