/* Cours : Physique — M1 : Cinématique du point */
window.OSCILLO_COURSES = window.OSCILLO_COURSES || [];
window.OSCILLO_COURSES.push({
  subject: "physique",
  id: "m1",
  name: "Cinématique du point",
  cards: [
    {id:"def-point-materiel-referentiel", type:"def", q:"Définir point matériel et référentiel", a:"Point matériel : système dont on peut négliger les dimensions et qui ne tourne pas sur lui-même.<br>Référentiel : solide de référence auquel on associe un repère d'espace (trois axes concourants rigidement liés) et une horloge pour mesurer le temps."},
    {id:"def-base-orthonormee-directe", type:"def", q:"Conditions pour qu'une base $(\\vec{u_1},\\vec{u_2},\\vec{u_3})$ soit orthonormée directe", a:"Orthogonale : $\\vec{u_1}\\cdot\\vec{u_2}=\\vec{u_1}\\cdot\\vec{u_3}=\\vec{u_2}\\cdot\\vec{u_3}=0$.<br>Normée : $\\|\\vec{u_1}\\|=\\|\\vec{u_2}\\|=\\|\\vec{u_3}\\|=1$.<br>Directe : $\\vec{u_1}\\wedge\\vec{u_2}=\\vec{u_3}$, $\\vec{u_2}\\wedge\\vec{u_3}=\\vec{u_1}$, $\\vec{u_3}\\wedge\\vec{u_1}=\\vec{u_2}$."},
    {id:"def-vecteur-position-trajectoire", type:"def", q:"Définir le vecteur position et la trajectoire d'un point matériel", a:"Vecteur position : $\\overrightarrow{OM}$.<br>Trajectoire : ensemble des positions occupées par le point au cours du mouvement."},
    {id:"formule-vecteur-vitesse", type:"formule", q:"Définition du vecteur vitesse (formule générale)", a:"$$\\vec{v}_{/\\mathcal{R}}(M)=\\left.\\dfrac{d\\overrightarrow{OM}}{dt}\\right|_{\\mathcal{R}}$$ Pendant $dt$, $M$ se déplace de $d\\overrightarrow{OM}=\\vec{v}\\,dt$. Le vecteur vitesse est tangent à la trajectoire à tout instant."},
    {id:"formule-vecteur-acceleration", type:"formule", q:"Définition du vecteur accélération (formule générale)", a:"$$\\vec{a}_{/\\mathcal{R}}(M)=\\left.\\dfrac{d\\vec{v}}{dt}\\right|_{\\mathcal{R}}=\\left.\\dfrac{d^2\\overrightarrow{OM}}{dt^2}\\right|_{\\mathcal{R}}$$"},
    {id:"formule-cartesiennes", type:"formule", q:"Position, vitesse et accélération en coordonnées cartésiennes", a:"$$\\overrightarrow{OM}=x\\vec{u_x}+y\\vec{u_y}+z\\vec{u_z}$$ $$\\vec{v}=\\dot{x}\\vec{u_x}+\\dot{y}\\vec{u_y}+\\dot{z}\\vec{u_z}$$ $$\\vec{a}=\\ddot{x}\\vec{u_x}+\\ddot{y}\\vec{u_y}+\\ddot{z}\\vec{u_z}$$"},
    {id:"formule-base-polaire", type:"formule", q:"Base polaire : expressions de $\\vec{u_r}$, $\\vec{u_\\theta}$ et leurs dérivées temporelles", a:"$$\\vec{u_r}=\\cos\\theta\\,\\vec{u_x}+\\sin\\theta\\,\\vec{u_y}, \\quad \\vec{u_\\theta}=-\\sin\\theta\\,\\vec{u_x}+\\cos\\theta\\,\\vec{u_y}$$ $$\\dfrac{d\\vec{u_r}}{dt}=\\dot\\theta\\,\\vec{u_\\theta}, \\qquad \\dfrac{d\\vec{u_\\theta}}{dt}=-\\dot\\theta\\,\\vec{u_r}$$"},
    {id:"formule-polaires-cinematique", type:"formule", q:"Position, vitesse et accélération en coordonnées polaires", a:"$$\\overrightarrow{OM}=r\\vec{u_r}$$ $$\\vec{v}=\\dot r\\,\\vec{u_r}+r\\dot\\theta\\,\\vec{u_\\theta}$$ $$\\vec{a}=\\left(\\ddot r-r\\dot\\theta^2\\right)\\vec{u_r}+\\left(2\\dot r\\dot\\theta+r\\ddot\\theta\\right)\\vec{u_\\theta}$$"},
    {id:"formule-cylindriques", type:"formule", q:"Position, vitesse et accélération en coordonnées cylindriques", a:"$$\\overrightarrow{OM}=r\\vec{u_r}+z\\vec{u_z}$$ $$\\vec{v}=\\dot r\\,\\vec{u_r}+r\\dot\\theta\\,\\vec{u_\\theta}+\\dot z\\,\\vec{u_z}$$ $$\\vec{a}=\\left(\\ddot r-r\\dot\\theta^2\\right)\\vec{u_r}+\\left(2\\dot r\\dot\\theta+r\\ddot\\theta\\right)\\vec{u_\\theta}+\\ddot z\\,\\vec{u_z}$$"},
    {id:"def-base-frenet", type:"def", q:"Base de Frenet : définition et expressions de $\\vec{v}$ et $\\vec{a}$", a:"Base locale $(\\vec{T},\\vec{N})$ liée à la trajectoire. $$\\vec{v}=v\\vec{T} \\qquad \\vec{a}=\\dfrac{dv}{dt}\\vec{T}+\\dfrac{v^2}{R}\\vec{N}$$ $R$ : rayon de courbure de la trajectoire en $M$."},
    {id:"formule-spheriques", type:"formule", q:"Position et vitesse en coordonnées sphériques", a:"$$\\overrightarrow{OM}=r\\vec{u_r}$$ $$\\vec{v}=\\dot r\\,\\vec{u_r}+r\\dot\\theta\\,\\vec{u_\\theta}+r\\sin(\\theta)\\dot\\varphi\\,\\vec{u_\\varphi}$$"},
    {id:"methode-choisir-systeme-coordonnees", type:"méthode", q:"Méthode : comment choisir le système de coordonnées adapté à un problème de cinématique ?", a:"Cartésiennes : mouvement rectiligne ou décomposable selon des axes fixes (ex. chute libre).<br>Polaires/cylindriques : mouvement présentant une symétrie de révolution autour d'un axe, ou trajectoire circulaire/en spirale (r et θ variables).<br>Frenet : utile dès qu'on connaît la trajectoire géométrique et qu'on veut relier vitesse/accélération à sa courbure, indépendamment du repère.<br>Sphériques : mouvement avec symétrie autour d'un point (ex. force centrale en 3D)."}
  ]
});
