/* Cours : Physique — T2 : Échanges énergétiques et premier principe */
window.OSCILLO_COURSES = window.OSCILLO_COURSES || [];
window.OSCILLO_COURSES.push({
  subject: "physique",
  id: "t2",
  name: "Échanges énergétiques et premier principe",
  cards: [
    {id:"formule-travail-pression", type:"formule", q:"Travail des forces de pression : cas général et cas particuliers", a:"Élémentaire : $$\\delta W_P=-P_{ext}\\,dV$$ Général : $$W_P=-\\int_{V_i}^{V_f} P_{ext}\\,dV$$ Isochore : $W_P=0$.<br>Monobare : $W_P=-P_{ext}\\Delta V$.<br>Quasi-statique : $W_P=-\\int_{V_i}^{V_f} P\\,dV$.<br>Isobare : $W_P=-P\\Delta V$."},
    {id:"def-transfert-thermique", type:"def", q:"Définir le transfert thermique et ses modes", a:"Énergie échangée sans intervention d'une action mécanique mesurable à l'échelle macroscopique.<br>Conduction : transmission de proche en proche (milieu matériel).<br>Convection : mouvement de brassage qui uniformise la température (fluides).<br>Rayonnement : énergie transportée par une onde électromagnétique.<br>Transformation adiabatique : aucun échange d'énergie par transfert thermique avec l'extérieur."},
    {id:"formule-premier-principe", type:"formule", q:"Énoncer le premier principe de la thermodynamique et ses cas particuliers", a:"Énoncé général : $$\\Delta E_c+\\Delta U=W+Q$$ Système au repos : $\\Delta U=W+Q$.<br>Transformation cyclique : $\\Delta U=0$.<br>Transformation adiabatique : $\\Delta U=W$.<br>Isochore sans travail autre que les forces de pression : $\\Delta U=Q$.<br>Transformation infinitésimale : $dU=\\delta W+\\delta Q$."},
    {id:"def-enthalpie", type:"def", q:"Définir l'enthalpie $H$ et son cas monobare, et la capacité thermique $C_P$", a:"$$H=U+PV$$ Transformation monobare sans travail autre que les forces de pression : $\\Delta H=Q$. Capacité thermique à pression constante : $$C_P=\\left(\\dfrac{\\partial H}{\\partial T}\\right)_P$$"},
    {id:"formule-gp-enthalpie", type:"formule", q:"Enthalpie molaire d'un gaz parfait et deuxième loi de Joule", a:"$$H_m=U_m+RT$$ Deuxième loi de Joule : l'enthalpie molaire d'un gaz parfait ne dépend que de la température."},
    {id:"formule-relation-mayer", type:"formule", q:"Relation de Mayer et expressions de $C_v$, $C_P$ pour un gaz parfait", a:"$$C_P=C_v+nR \\quad\\text{(relation de Mayer)}$$ $$\\gamma=\\dfrac{C_P}{C_v} \\quad\\text{(exposant adiabatique)}$$ $$C_v=\\dfrac{nR}{\\gamma-1}, \\qquad C_P=\\dfrac{\\gamma nR}{\\gamma-1}$$"},
    {id:"propriete-phase-condensee-enthalpie", type:"propriété", q:"Enthalpie et capacités thermiques d'une phase condensée indilatable et incompressible", a:"$$\\Delta H\\approx\\Delta U, \\qquad H_m=H_m(T), \\qquad C_P\\approx C_v$$"},
    {id:"methode-calcul-travail-pression", type:"méthode", q:"Méthode : quelle formule utiliser pour calculer $W_P$ selon le type de transformation ?", a:"1. Identifier le type de transformation (isochore, monobare, quasi-statique/isobare).<br>2. Isochore ($V$ constant) → $W_P=0$ directement.<br>3. Monobare ($P_{ext}$ constante, mais le système peut ne pas être à l'équilibre en cours de route) → $W_P=-P_{ext}\\Delta V$.<br>4. Quasi-statique (le système est à chaque instant à l'équilibre, $P=P_{ext}$) → il faut connaître la loi $P(V)$ (souvent via $PV=nRT$ ou $PV^\\gamma=\\text{cste}$) pour intégrer $W_P=-\\int P\\,dV$."},
    {id:"methode-application-premier-principe", type:"méthode", q:"Méthode : appliquer le premier principe à une transformation thermodynamique", a:"1. Définir clairement le système et le référentiel d'étude.<br>2. Identifier le type de transformation (adiabatique, isochore, monobare...) pour simplifier $\\Delta U=W+Q$.<br>3. Calculer $\\Delta U$ via $C_v\\Delta T$ (GP ou phase condensée) ou $\\Delta H$ via $C_P\\Delta T$ si plus adapté (monobare).<br>4. Calculer $W$ (travail des forces de pression, cf. méthode dédiée).<br>5. En déduire $Q$ (ou l'inconnue manquante) par différence."}
  ]
});
