/* Cours : Physique — EL4 : Oscillateurs */
window.OSCILLO_COURSES = window.OSCILLO_COURSES || [];
window.OSCILLO_COURSES.push({
  subject: "physique",
  id: "el4",
  name: "Oscillateurs",
  year: "spe",
  cards: [
    {id:"def-oscillateur", type:"def", q:"Définition d'un oscillateur", a:"Système autonome (sans excitation externe) capable de générer un signal périodique en sortie, à partir de sa seule alimentation continue (pas de signal d'entrée périodique imposé)."},
    {id:"def-deux-types-oscillateurs", type:"def", q:"Deux types d'oscillateurs", a:"Oscillateurs quasi-sinusoïdaux (signal de sortie proche d'une sinusoïde) et oscillateurs à relaxation (signal de sortie non sinusoïdal, typiquement créneaux/triangles, résultant de basculements successifs)."},
    {id:"propriete-oscillateur-harmonique-irrealisable", type:"propriété", q:"Justifier qu'un oscillateur harmonique théorique (boucle sans perte) est irréalisable expérimentalement", a:"Un oscillateur harmonique correspond à une boucle sans perte (partie réelle nulle des pôles), situation limite instable : la moindre imperfection (tolérances, bruit) fait dévier de cette condition idéale, menant soit à un amortissement (extinction), soit à une divergence (saturation). Le régime purement sinusoïdal stable exact n'est jamais atteint sans un mécanisme de régulation non-linéaire (saturation)."},
    {id:"methode-resistance-negative", type:"méthode", q:"Méthode pour calculer l'impédance d'entrée Ze=ue/ie du montage à résistance négative", a:"On suppose l'ALI idéal en régime linéaire (rétroaction sur l'entrée −), on exprime $V_+=u_e$ et $V_-=u_e$ (égalité des potentiels), on calcule le courant $i_e$ injecté en fonction de $u_e$ et des résistances via les lois des nœuds/mailles, puis $Z_e=u_e/i_e$.<br>Le résultat est de la forme $Z_e=-kR$ (résistance négative), le signe négatif provenant de la rétroaction positive du montage."},
    {id:"methode-construction-oscillateur-resistance-negative", type:"méthode", q:"Construire un oscillateur harmonique à partir de la résistance négative, et limite du raisonnement", a:"On associe la résistance négative à un circuit LC (résonateur) : l'énergie dissipée par les pertes résistives du LC est exactement compensée par l'apport d'énergie de la résistance négative, entretenant en théorie des oscillations sinusoïdales non amorties.<br>En pratique, ce réglage exact (compensation parfaite) est instable : la moindre variation fait diverger ou s'amortir le système."},
    {id:"def-oscillateur-structure-bloc-temporelle", type:"def", q:"Structure bloc (temporelle) d'un oscillateur quasi-sinusoïdal, et les deux équations liant u(t) et s(t)", a:"Structure en boucle fermée : un bloc amplificateur (gain A) et un bloc filtre (fonction B, rétroaction), le signal de sortie du filtre étant réinjecté en entrée de l'amplificateur.<br>Équations : $s=A\\cdot e'$ (amplificateur) et $e'=B[s]$ (filtre appliqué à s, réinjecté), où $e'$ est l'entrée effective de l'amplificateur."},
    {id:"methode-eq-diff-critere-apparition", type:"méthode", q:"Établir l'équation différentielle pour s(t) et le critère d'apparition des oscillations (vision temporelle)", a:"En combinant les relations des deux blocs (amplificateur + filtre décrit par une équation différentielle), on élimine $e'$ pour obtenir une équation différentielle homogène en $s(t)$.<br>Critère d'apparition : il faut que le gain de boucle compense exactement (ou dépasse légèrement) les pertes, soit un coefficient d'amortissement négatif ou nul dans l'équation caractéristique (solutions oscillantes non amorties, voire croissantes au démarrage)."},
    {id:"def-critere-barkhausen", type:"def", q:"Critère de Barkhausen (vision fréquentielle) pour des oscillations sinusoïdales stables", a:"En notant A le gain complexe de l'amplificateur et $B(j\\omega)$ la fonction de transfert du filtre de rétroaction, la condition d'oscillation stable est $$A\\cdot B(j\\omega_0)=1$$ soit deux équations réelles : $$|A\\cdot B(j\\omega_0)|=1 \\quad\\text{(module)}\\quad\\text{et}\\quad \\arg(A\\cdot B(j\\omega_0))=0\\ [2\\pi]\\quad\\text{(phase)}$$"},
    {id:"methode-identification-blocs-resistance-negative", type:"méthode", q:"Identifier le bloc filtre et le bloc amplificateur sur l'oscillateur à résistance négative — dimension des signaux", a:"Le bloc « amplificateur » correspond à la résistance négative (relation tension-courant, $Z_e$), le bloc « filtre » correspond au circuit LC résonant.<br>Les deux signaux bouclés n'ont pas nécessairement la même dimension : le « gain de boucle » est ici homogène à une impédance (ou son inverse), pas un rapport sans dimension."},
    {id:"methode-pont-wien", type:"méthode", q:"Oscillateur à pont de Wien : étage amplificateur, étage filtre, condition d'oscillation", a:"Étage amplificateur : montage non-inverseur de gain $A=1+\\dfrac{R_2}{R_1}$.<br>Étage filtre (pont de Wien) : $$B(j\\omega)=\\dfrac{1}{3+j\\left(RC\\omega-\\dfrac{1}{RC\\omega}\\right)}$$ Condition d'oscillation (Barkhausen, $AB=1$) : phase nulle pour $\\omega_0=\\dfrac{1}{RC}$ (pulsation d'oscillation), et module unité pour $A=3$, soit $R_2=2R_1$."},
    {id:"propriete-insuffisance-bruit", type:"propriété", q:"Est-il possible d'obtenir expérimentalement l'égalité AB=1 exacte ? Comment justifier que les conditions initiales ne soient pas nulles ?", a:"Non, en pratique l'égalité exacte $AB=1$ est un réglage instable ; le bruit électronique intrinsèque (agitation thermique, bruit des composants) fournit toujours un signal initial non nul qui sert de germe aux oscillations, même sans excitation externe volontaire."},
    {id:"formule-critere-demarrage", type:"formule", q:"Critère de démarrage des oscillations (équation temporelle et équation complexe)", a:"Il faut un léger excès de gain par rapport à la condition théorique exacte, pour compenser les pertes réelles : en pratique $A>3$ pour le pont de Wien (gain de boucle légèrement supérieur à 1, coefficient d'amortissement négatif dans l'équation différentielle → solutions initialement croissantes). En complexe : $|AB(j\\omega_0)|>1$."},
    {id:"propriete-role-non-linearites-demarrage", type:"propriété", q:"Pourquoi les effets de saturation permettent-ils les oscillations (stabilisation d'amplitude) ?", a:"Le démarrage se fait avec un gain de boucle légèrement supérieur à 1 (croissance exponentielle initiale de l'amplitude) ; quand l'amplitude atteint la zone de saturation de l'ALI, le gain effectif diminue (non-linéarité), ramenant le gain de boucle moyen à 1 : les non-linéarités stabilisent ainsi l'amplitude à une valeur constante (cycle limite)."},
    {id:"def-representation-signal-sature", type:"def", q:"Représenter schématiquement le signal en fonction du temps pour un oscillateur quasi-sinusoïdal en régime établi", a:"Le signal croît d'abord de façon exponentielle (démarrage, amplitude croissante) puis se stabilise à amplitude constante en régime permanent, sa forme restant proche d'une sinusoïde (légèrement aplatie près des sommets si la saturation intervient fortement, « écrêtage »)."},
    {id:"def-oscillateur-relaxation-position", type:"def", q:"Position du problème pour un oscillateur à relaxation (exemple vase de tantale) : description et deux phases", a:"Le vase de tantale : un réservoir se remplit progressivement (phase 1) jusqu'à un seuil, puis se vide brutalement par effet siphon (phase 2), puis recommence à se remplir : cycle périodique non sinusoïdal (dents de scie), par alternance de deux régimes séparés par des basculements brusques."},
    {id:"def-schema-principe-relaxation", type:"def", q:"Schéma de principe d'un oscillateur à relaxation", a:"Association d'un comparateur à hystérésis (élément bistable à seuils, « mémoire ») et d'un intégrateur (élément qui charge/décharge progressivement, ex. circuit RC) : l'intégrateur évolue lentement jusqu'à atteindre un seuil de basculement du comparateur, qui inverse alors l'état, relançant l'intégrateur en sens opposé — cycle répété périodiquement."},
    {id:"methode-montage-2ali", type:"méthode", q:"Montage à 2 ALI : identifier le comparateur à hystérésis et l'intégrateur, déterminer la fréquence", a:"Le 1er ALI (rétroaction positive, pont diviseur $R_1,R_2$) forme le comparateur à hystérésis (sortie bistable $\\pm V_{sat}$, seuils $\\pm\\dfrac{R_1}{R_2}V_{sat}$).<br>Le 2nd ALI (montage intégrateur R,C) intègre la sortie du comparateur, produisant un signal triangulaire de pentes $\\pm\\dfrac{V_{sat}}{RC}$.<br>Mise en équation (temps pour passer d'un seuil à l'autre) : $$T=\\dfrac{4R_1RC}{R_2}\\quad\\Rightarrow\\quad f=\\dfrac{1}{T}=\\dfrac{R_2}{4R_1RC}$$"},
    {id:"methode-multivibrateur-astable", type:"méthode", q:"Multivibrateur astable (1 seul ALI) : justifier la saturation, identifier l'intégrateur, déterminer la fréquence", a:"Un seul ALI : rétroaction positive (comparateur à hystérésis, pont $R_1,R_2$ sur l'entrée +) et charge/décharge d'un condensateur C à travers une résistance R sur l'entrée −, alimentée par la sortie saturée elle-même (le RC fait office d'intégrateur approché).<br>L'ALI sature nécessairement car il n'y a pas de rétroaction négative pure sur − (le RC ne ramène pas $\\varepsilon$ à 0). La tension aux bornes de C évolue entre les seuils $\\pm\\dfrac{R_1}{R_1+R_2}V_{sat}$, de constante de temps $\\tau=RC$, d'où la période $$T=2RC\\ln\\left(1+\\dfrac{2R_1}{R_2}\\right)$$"}
  ]
});
