/* Cours : Physique — M6 : Mouvement dans un champ de force centrale */
window.OSCILLO_COURSES = window.OSCILLO_COURSES || [];
window.OSCILLO_COURSES.push({
  subject: "physique",
  id: "m6",
  name: "Mouvement dans un champ de force centrale",
  cards: [
    {id:"def-force-centrale", type:"def", q:"Définir une force centrale et donner des exemples", a:"Force dont la droite d'action passe constamment par un point fixe (le centre de force) : $\\vec{F}=F(r,\\theta,\\varphi)\\vec{u_r}$.<br>Exemples : tension d'un fil, force de rappel d'un ressort, interaction gravitationnelle, interaction coulombienne (centre de force = point d'attache ou point exerçant la force)."},
    {id:"formule-conservation-moment-cinetique", type:"formule", q:"Montrer que le moment cinétique se conserve pour une force centrale, et conséquence géométrique", a:"$\\vec{\\mathcal{M}_O}(\\vec{F})=\\overrightarrow{OM}\\wedge\\vec{F}=r\\vec{u_r}\\wedge F_r\\vec{u_r}=\\vec{0}$. Par le TMC : $$\\dfrac{d\\vec{L_O}(M)}{dt}=\\vec{0} \\Rightarrow \\vec{L_O}(M)=\\text{cste}$$ ⇒ la trajectoire est plane (plan passant par O, perpendiculaire à $\\vec{L_O}$)."},
    {id:"formule-loi-aires", type:"formule", q:"Loi des aires : constante des aires et vitesse aréolaire", a:"En polaires : $$\\vec{L_O}(M)=mr^2\\dot\\theta\\,\\vec{u_z} \\Rightarrow C=r^2\\dot\\theta=\\text{cste}$$ Vitesse aréolaire : $$\\dfrac{dA}{dt}=\\dfrac{|C|}{2}$$ Le vecteur position balaie des aires égales pendant des durées égales."},
    {id:"formule-energie-potentielle-effective", type:"formule", q:"Définir l'énergie potentielle effective pour un mouvement à force centrale conservative", a:"$$E_m=\\dfrac12 m\\dot r^2+\\dfrac{mC^2}{2r^2}+E_p(r)=\\dfrac12 m\\dot r^2+E_{p,eff}(r)$$ avec $$E_{p,eff}(r)=\\dfrac{mC^2}{2r^2}+E_p(r)$$ ⇒ le problème radial devient un mouvement unidimensionnel équivalent."},
    {id:"formule-force-newtonienne", type:"formule", q:"Définir une force newtonienne et son énergie potentielle", a:"$$\\vec{F}=\\dfrac{K}{r^2}\\vec{u_r}, \\qquad E_p=\\dfrac{K}{r}+\\text{cste (nulle à l'infini)}$$ Gravitation : $K=-Gm_1m_2$ (toujours attractive). Coulomb : $K=\\dfrac{q_1q_2}{4\\pi\\varepsilon_0}$ (signe selon les charges)."},
    {id:"def-etats-lies-diffusion", type:"def", q:"Force newtonienne attractive : distinguer état lié et état de diffusion selon $E_m$", a:"$E_m<0$ : état lié. Si $E_m=E_{p,eff}^{min}$, mouvement circulaire ($r$ constant) ; sinon mouvement elliptique.<br>$E_m\\ge 0$ : état de diffusion. Si $E_m=0$, mouvement parabolique ; sinon hyperbolique.<br>Force répulsive : état de diffusion quel que soit $E_m$."},
    {id:"def-lois-kepler", type:"def", q:"Énoncer les trois lois de Kepler (force newtonienne attractive)", a:"1ère loi : chaque planète décrit une trajectoire elliptique dont le Soleil est un foyer.<br>2ème loi (loi des aires) : le vecteur Soleil-planète balaie des aires égales pendant des durées égales.<br>3ème loi : $\\dfrac{T^2}{a^3}$ est le même pour toutes les planètes du système solaire ($T$ = période, $a$ = demi-grand axe)."},
    {id:"formule-vitesses-cosmiques", type:"formule", q:"Première et deuxième vitesses cosmiques (à la surface de la Terre)", a:"1ère vitesse cosmique (mise en orbite) : $$v_c=\\sqrt{\\dfrac{GM_T}{R_T}}$$ 2ème vitesse cosmique (libération) : $$v_l=\\sqrt{\\dfrac{2GM_T}{R_T}}=\\sqrt2\\,v_c$$"},
    {id:"def-satellite-geostationnaire", type:"def", q:"Conditions pour qu'un satellite soit géostationnaire", a:"1. Plan de l'orbite dans le plan de l'équateur.<br>2. Mouvement synchrone avec la rotation terrestre.<br>3. Mouvement circulaire ⇒ une seule altitude possible."},
    {id:"methode-etudier-force-centrale", type:"méthode", q:"Méthode générale pour étudier un mouvement à force centrale", a:"1. Vérifier que la force est centrale et conservative.<br>2. Utiliser la conservation du moment cinétique pour montrer que la trajectoire est plane et introduire la constante des aires $C=r^2\\dot\\theta$.<br>3. Utiliser la conservation de l'énergie mécanique pour se ramener à un problème radial 1D avec $E_{p,eff}(r)$.<br>4. Analyser le graphe de $E_{p,eff}(r)$ face à $E_m$ pour déterminer la nature du mouvement (lié/diffusion, circulaire/elliptique/parabolique/hyperbolique)."}
  ]
});
