/* Cours : Sciences de l'ingénieur — Ch1 : Ingénierie système, analyse fonctionnelle et structurelle */
window.OSCILLO_COURSES = window.OSCILLO_COURSES || [];
window.OSCILLO_COURSES.push({
  subject: "si",
  id: "si1",
  name: "Ingénierie système : analyse fonctionnelle et structurelle",
  cards: [
    {id:"def-systeme", type:"def", q:"Définition d'un système (norme ISO/IEC 15288)", a:"Un arrangement d'éléments en interaction organisée pour atteindre un ou plusieurs objectifs définis."},
    {id:"def-systeme-naturel-artificiel", type:"def", q:"Différence entre système naturel et système artificiel", a:"Naturel : non créé par l'homme (ex : système sanguin, système solaire).<br>Artificiel (ou industriel) : créé par l'homme pour remplir des fonctions précises."},
    {id:"def-eme-frontiere", type:"def", q:"Définir les Éléments du Milieu Extérieur (EME) et la frontière d'un système", a:"Un système interagit toujours avec l'extérieur : les EME sont les éléments avec lesquels il échange. La frontière du système délimite ce qui en fait partie de ce qui n'en fait pas partie."},
    {id:"def-systeme-simple-complexe", type:"def", q:"Différence entre système simple et système complexe", a:"Système simple : une entrée permet de trouver la sortie par analyse déductive (solution unique, esprit de logique).<br>Système complexe : grand nombre d'entités en interaction qui empêchent de prévoir le comportement par le calcul seul — nécessite modélisation."},
    {id:"def-criteres-techno-eco", type:"def", q:"Les 4 critères technico-économiques pris en compte lors de la conception", a:"La durée de vie, le coût, la fiabilité, la quantité."},
    {id:"def-ingenierie-systeme", type:"def", q:"Définition de l'Ingénierie Système", a:"Démarche méthodologique générale englobant l'ensemble des activités adéquates pour concevoir, faire évoluer et vérifier un système apportant une solution économique et performante aux besoins d'un client, en satisfaisant toutes les parties prenantes."},
    {id:"def-competences-ingenieur", type:"def", q:"Les 6 compétences de la démarche d'ingénieur en CPGE", a:"Analyser, Modéliser, Résoudre, Expérimenter, Concevoir, Communiquer — avec en leur centre les Performances (attendues / mesurées / simulées)."},
    {id:"def-cycle-vie-cycle-v", type:"def", q:"Définir le cycle de vie et le cycle en V d'un système", a:"Cycle de vie : les différentes étapes de la vie d'un produit, de l'identification du besoin jusqu'au recyclage.<br>Cycle en V : présente à travers ces étapes la démarche de l'ingénieur mise en place pour la réalisation du produit."},
    {id:"def-eco-conception", type:"def", q:"Définition de l'éco-conception", a:"Démarche visant à réduire l'impact environnemental d'un système sur l'ensemble de son cycle de vie (norme ISO 14040), de l'extraction des matières premières jusqu'au traitement en fin de vie."},
    {id:"def-sysml", type:"def", q:"Qu'est-ce que le langage SysML et ses objectifs ?", a:"Langage de modélisation (2006) regroupant dans un modèle commun à tous les corps de métier les spécifications, contraintes et paramètres d'un système. Objectifs : langage commun normalisé, réduction des ambiguïtés, accès intuitif au cahier des charges."},
    {id:"formulaire-sysml-9-diagrammes", type:"formule", q:"Les 9 types de diagrammes SysML, par catégorie", a:"Fonctionnels : exigence (req), cas d'utilisation (uc).<br>Comportementaux : séquence (seq), machine d'état (stm), activités (act).<br>Structurels : définition de blocs (bdd), bloc interne (ibd), paquetage (pkg), paramétrique (par)."},
    {id:"formulaire-liens-sysml", type:"formule", q:"Les liens géométriques classiques entre éléments SysML : association, dépendance, agrégation, composition, généralisation, conteneur", a:"Association : relation d'égal à égal (A utilise B).<br>Dépendance : A dépend de B.<br>Agrégation : A entre dans la composition de B sans être indispensable.<br>Composition : A entre dans la composition de B et lui est indispensable.<br>Généralisation : A est une sorte de B.<br>Conteneur : B contient A."},
    {id:"def-besoin", type:"def", q:"Définition d'un besoin (norme NF X 50-150)", a:"Une nécessité ou un désir éprouvé par un utilisateur."},
    {id:"methode-valider-besoin", type:"méthode", q:"Les 3 questions à se poser pour valider un besoin", a:"1. Pourquoi le produit existe-t-il ?<br>2. Qu'est-ce qui pourrait faire évoluer le besoin ?<br>3. Qu'est-ce qui pourrait le faire disparaître ?"},
    {id:"def-cdcf-exigence", type:"def", q:"Définir le Cahier des Charges Fonctionnel (CdCF) et une exigence", a:"CdCF : document formalisant avec précision le besoin du demandeur, lien de compréhension entre entreprise et client.<br>Une exigence est caractérisée par : un critère (grandeur mesurable), un niveau (valeur attendue), une flexibilité (écart acceptable)."},
    {id:"def-diagramme-uc", type:"def", q:"Rôle du diagramme des cas d'utilisation (uc) et ses relations", a:"Répond à « quels services rend le système ? ». Définit les acteurs (principaux à gauche, secondaires à droite de la frontière) et les cas d'utilisation, reliés par include (inclusion), extend (extension), ou généralisation/spécialisation."},
    {id:"def-diagramme-req", type:"def", q:"Rôle du diagramme d'exigences (req) et ses relations", a:"Représente toutes les exigences du système (environnementales, économiques, fonctionnelles, techniques). Relations : contenance (décompose une exigence composite), raffinement «refine» (ajout de précision), dérivation «derivereq» (relie des exigences de niveaux différents)."},
    {id:"def-diagramme-bdd", type:"def", q:"Rôle du diagramme de définition de bloc (bdd) et ses 4 liens", a:"Répond à « qui est composé de quoi ? » — décrit la structure interne du système. 4 liens : composition (losange plein, indispensable), agrégation (losange vide, non indispensable), association (sans contenance), généralisation (factorise des propriétés communes)."},
    {id:"def-multiplicite-instance", type:"def", q:"Définir la multiplicité d'une relation et une instance", a:"Multiplicité : indication du nombre d'instances pouvant participer à une relation (sous forme d'intervalle).<br>Instance : exemplaire d'un bloc possédant une identité propre (ex : une voiture possède 4 roues)."},
    {id:"def-diagramme-ibd", type:"def", q:"Rôle du diagramme de bloc interne (ibd) et les ports", a:"Explicite les flux (matière/information/énergie) entre blocs de même niveau. Ports de flux (carré + flèche) : échanges de matière/info/énergie. Ports standards (carré simple) : services invoqués par un autre bloc."},
    {id:"def-diagramme-parametrique-package", type:"def", q:"Rôle des diagrammes paramétrique (par) et de package (pkg)", a:"Paramétrique : représente des contraintes (équations) sur des valeurs de paramètres système (performance, fiabilité, masse...).<br>Package : regroupe les éléments d'un modèle par type/fonction ; relations de contenance et dépendance entre packages."}
  ]
});
