/* Cours : Sciences de l'ingénieur — Ch3 : Introduction à l'automatique */
window.OSCILLO_COURSES = window.OSCILLO_COURSES || [];
window.OSCILLO_COURSES.push({
  subject: "si",
  id: "si3",
  name: "Introduction à l'automatique",
  cards: [
    {id:"def-systeme-automatise", type:"def", q:"Définition d'un système automatisé", a:"Système réalisant des opérations et pour lequel l'intervention humaine est limitée à la programmation du système et à son réglage préalable."},
    {id:"def-buts-systemes-automatises", type:"def", q:"Les 3 buts des systèmes automatisés", a:"Réaliser des tâches impossibles ou dangereuses pour l'homme ; réaliser des tâches pénibles ou répétitives ; améliorer la précision des tâches."},
    {id:"def-classification-info", type:"def", q:"Classification des systèmes automatisés selon la nature de l'information traitée", a:"Grandeurs analogiques : valeurs réelles continues (ex : 25,2°C).<br>Grandeurs numériques : nombre fini de valeurs (suite de nombres binaires).<br>Systèmes logiques (0 ou 1) : combinatoires (sortie dépend uniquement de l'entrée actuelle) ou séquentiels (dépend aussi des évolutions précédentes)."},
    {id:"def-systeme-asservi", type:"def", q:"Définition d'un système asservi", a:"Système automatisé bouclé qui compare la consigne à l'état réel du système de manière à le corriger efficacement, en fonction de l'écart entre consigne et état du système."},
    {id:"def-structure-boucle-retour", type:"def", q:"Structure d'un système asservi : chaîne directe et chaîne de retour", a:"Chaîne d'action (ou directe) : Consigne → Écart ε → Correcteur → Système → Sortie.<br>Chaîne de retour (ou d'information) : la sortie est mesurée par un Capteur et renvoyée pour calculer l'écart. On parle de commande en chaîne fermée."},
    {id:"def-regulation-poursuite", type:"def", q:"Différence entre système asservi de régulation et système asservi suiveur (poursuite)", a:"Régulation : consigne d'entrée fixe, destiné à maintenir une sortie constante (ex : régulation de température).<br>Suiveur/poursuite : consigne d'entrée variable en permanence, objectif d'ajuster la sortie à l'entrée (ex : machine-outil à commande numérique)."},
    {id:"def-impulsion-dirac", type:"def", q:"Définition de l'impulsion de Dirac et de la réponse impulsionnelle", a:"Impulsion de Dirac $\\delta(t)$ : $\\forall t\\neq 0, \\delta(t)=0$ — modélise une action de très courte durée (coup de marteau...).<br>La réponse à une impulsion de Dirac est appelée réponse impulsionnelle."},
    {id:"def-echelon-unite", type:"def", q:"Définition de l'échelon unité et de la réponse indicielle", a:"Échelon unité $u(t)$ : $u(t)=0$ pour $t<0$, $u(t)=1$ pour $t\\geq 0$ — modélise un signal qui passe de 0 à 1 très rapidement (interrupteur).<br>La réponse à un échelon unité est appelée réponse indicielle."},
    {id:"def-rampe-sinusoidale", type:"def", q:"Définition de la rampe de pente unitaire et de la fonction sinusoïdale", a:"Rampe : $r(t)=0$ pour $t<0$, $r(t)=t$ pour $t\\geq 0$.<br>Fonction sinusoïdale : $f(t)=u(t)\\cdot\\sin(\\omega t)$."},
    {id:"def-signaux-complexes", type:"def", q:"Comment modéliser un signal complexe à partir des signaux élémentaires ?", a:"Tout signal peut s'écrire comme une somme de signaux élémentaires (échelons, rampes) et de fonctions retardées $u(t-\\tau)$, dont le passage de 0 à 1 ne s'effectue qu'au temps $\\tau$."},
    {id:"def-criteres-performance", type:"def", q:"Les 4 critères de performance d'un système asservi", a:"Rapidité, précision, stabilité, amortissement."},
    {id:"def-rapidite", type:"def", q:"Définition de la rapidité et du temps de réponse à 5%", a:"Rapidité : temps que met le système à réagir à une variation brusque de l'entrée.<br>$t_{5\\%}$ : temps mis par le système pour se stabiliser dans la bande à $\\pm5\\%$ de la valeur du régime permanent."},
    {id:"def-precision-statique-position", type:"def", q:"Définition de l'écart statique en position", a:"$$\\varepsilon_s = \\lim_{t\\to+\\infty}(e(t)-s(t)) = \\lim_{t\\to+\\infty}(E_0\\cdot u(t)-s(t))$$ Un système régulateur est précis si l'écart statique est nul."},
    {id:"def-precision-statique-vitesse", type:"def", q:"Définition de l'écart de traînage (précision statique en vitesse)", a:"$$\\varepsilon_t = \\lim_{t\\to+\\infty}(e(t)-s(t))$$ (avec une entrée en rampe). On parle d'erreur en accélération si l'entrée est une parabole."},
    {id:"def-stabilite", type:"def", q:"Définition de la stabilité d'un système", a:"Un système est stable si, à une entrée bornée, correspond une sortie bornée. Le bouclage peut déstabiliser un système."},
    {id:"def-amortissement-depassement", type:"def", q:"Définition de l'amortissement et du taux de dépassement", a:"Amortissement : caractérisé par le rapport entre deux amplitudes successives des oscillations ; plus elles s'atténuent vite, plus le système est amorti.<br>$$D_\\% = \\left|\\dfrac{s(t_1)-s_\\infty}{s_\\infty}\\right|$$ (premier dépassement relatif, le plus couramment utilisé)"},
    {id:"propriete-bilan-performances", type:"propriété", q:"Comment les critères de performance (stabilité, amortissement, précision, rapidité) s'articulent-ils entre eux ?", a:"La stabilité est nécessaire pour pouvoir parler de précision et de rapidité. Un bon amortissement est signe d'un système stable et rapide. Ces critères ne sont en général pas tous compatibles entre eux : il faut trouver le meilleur compromis via le réglage du correcteur."}
  ]
});
