/* Cours : Sciences de l'ingénieur — Ch4 : Modélisation des SLCI */
window.OSCILLO_COURSES = window.OSCILLO_COURSES || [];
window.OSCILLO_COURSES.push({
  subject: "si",
  id: "si4",
  name: "Modélisation des SLCI",
  cards: [
    {id:"def-modelisation", type:"def", q:"Définition de la modélisation et ses 2 types de modèles", a:"La modélisation est la conception d'un modèle théorique.<br>Modèle de connaissance : obtenu à partir de lois physiques.<br>Modèle de comportement : identifié à partir de résultats expérimentaux."},
    {id:"def-slci-monovariable", type:"def", q:"Qu'est-ce qu'un système mono-variable dans le cadre des SLCI ?", a:"Un système qui ne possède qu'une seule entrée et qu'une seule sortie. Un système complexe peut être décomposé en sous-systèmes monovariables représentés par des blocs en série."},
    {id:"def-systeme-lineaire", type:"def", q:"Définition d'un système linéaire, et ses 2 principes", a:"Un système est linéaire si la fonction qui le décrit est elle-même linéaire.<br>Proportionnalité : si $e(t)\\to s(t)$, alors $\\lambda e(t)\\to\\lambda s(t)$.<br>Superposition : si $e_1(t)\\to s_1(t)$ et $e_2(t)\\to s_2(t)$, alors $e_1(t)+e_2(t)\\to s_1(t)+s_2(t)$."},
    {id:"def-systeme-linearise", type:"def", q:"Qu'est-ce qu'un système linéarisé ? Citer 3 non-linéarités classiques", a:"Un système dont on approche le comportement par un modèle linéaire sur une partie de sa zone de fonctionnement.<br>Non-linéarités classiques : saturation (butée mécanique), seuil (frottement), hystérésis (jeux mécaniques)."},
    {id:"def-systeme-continu-invariant", type:"def", q:"Définitions de système continu et système invariant", a:"Continu : les variations des grandeurs physiques sont définies à chaque instant (fonctions continues) — aussi appelé système analogique.<br>Invariant : les caractéristiques du système (masse, résistance...) ne varient pas avec le temps. Si $s(t)$ est la réponse à $e(t)$, alors $s(t-\\tau)$ est la réponse à $e(t-\\tau)$."},
    {id:"formule-premier-ordre", type:"formule", q:"Forme générale de l'équation différentielle d'un système du premier ordre", a:"$$\\tau\\dfrac{ds(t)}{dt}+s(t) = Ke(t)$$ avec $\\tau$ la constante de temps (en secondes) et $K$ le gain du système."},
    {id:"formule-second-ordre", type:"formule", q:"Forme générale de l'équation différentielle d'un système du second ordre", a:"$$\\dfrac{d^2s(t)}{dt^2}+2z\\omega_0\\dfrac{ds(t)}{dt}+\\omega_0^2s(t) = K\\omega_0^2e(t)$$ avec $\\omega_0$ la pulsation propre (rad/s), $z$ le coefficient d'amortissement (sans unité), $K$ le gain."},
    {id:"def-ordre-systeme", type:"def", q:"Forme générale d'un système linéaire continu asservi d'ordre $n$", a:"$$a_n\\dfrac{d^ns(t)}{dt^n}+...+a_0s(t) = b_m\\dfrac{d^me(t)}{dt^m}+...+b_0e(t)$$ $n$ est appelé ordre du système."},
    {id:"def-reponse-libre-forcee", type:"def", q:"Différence entre réponse libre et réponse forcée", a:"Réponse libre : solution générale de l'équation sans second membre, caractérise le régime transitoire (indépendante de l'excitation).<br>Réponse forcée : solution particulière avec second membre, caractérise le régime permanent."},
    {id:"def-transformee-laplace", type:"def", q:"Définition de la transformée de Laplace $F(p)$ d'une fonction $f(t)$", a:"$$F(p) = \\mathcal{L}[f(t)] = \\int_0^{\\infty} f(t)\\,e^{-pt}\\,dt$$ On travaille avec des fonctions causales : $f(t)=0$ pour $t<0$."},
    {id:"def-conditions-heaviside", type:"def", q:"Que signifie qu'une fonction vérifie les conditions de Heaviside ?", a:"Toutes les conditions initiales sont nulles : $f(0^+)=0$, $f'(0^+)=0$, $f''(0^+)=0$, etc."},
    {id:"propriete-laplace-linearite", type:"formule", q:"Propriété de linéarité de la transformée de Laplace", a:"$$\\mathcal{L}[a\\cdot f_1(t)+b\\cdot f_2(t)] = a\\cdot F_1(p)+b\\cdot F_2(p)$$"},
    {id:"propriete-laplace-retard", type:"formule", q:"Théorème du retard pour la transformée de Laplace", a:"$$\\mathcal{L}[f(t-\\tau)] = e^{-p\\tau}\\cdot F(p)$$"},
    {id:"propriete-laplace-derivee", type:"formule", q:"Transformée de Laplace d'une dérivée (conditions de Heaviside)", a:"$$\\mathcal{L}[f'(t)] = p\\cdot F(p) \\qquad \\mathcal{L}[f^{(n)}(t)] = p^n\\cdot F(p)$$ Dériver dans le domaine temporel = multiplier par $p$ dans le domaine de Laplace."},
    {id:"propriete-laplace-integrale", type:"formule", q:"Transformée de Laplace d'une intégrale (conditions initiales nulles)", a:"$$\\mathcal{L}\\left[\\int_0^t f(u)\\,du\\right] = \\dfrac{F(p)}{p}$$ Intégrer dans le domaine temporel = diviser par $p$ dans le domaine de Laplace."},
    {id:"propriete-theoremes-valeur", type:"propriété", q:"Théorèmes de la valeur initiale et de la valeur finale", a:"Valeur initiale : $\\lim_{t\\to 0^+} f(t) = \\lim_{p\\to+\\infty} pF(p)$<br>Valeur finale : $\\lim_{t\\to+\\infty} f(t) = \\lim_{p\\to 0^+} pF(p)$ (ne s'applique qu'aux systèmes stables)"},
    {id:"def-fonction-transfert", type:"def", q:"Définition de la fonction de transfert (transmittance) $H(p)$", a:"$$H(p) = \\dfrac{S(p)}{E(p)} = \\dfrac{b_mp^m+...+b_0}{a_np^n+...+a_0}$$ Rapport entre la sortie et l'entrée dans le domaine de Laplace, avec conditions initiales nulles."},
    {id:"def-forme-canonique", type:"def", q:"Première forme canonique de la fonction de transfert", a:"$$H(p) = \\dfrac{K}{p^\\alpha}\\cdot\\dfrac{(1+...+\\tilde{b}_mp^m)}{(1+...+\\tilde{a}_{n'}p^{n'})}$$ avec $n=n'+\\alpha$ l'ordre, $\\alpha$ la classe du système, $K$ le gain (statique si $\\alpha=0$)."},
    {id:"def-forme-canonique-2", type:"def", q:"Deuxième forme canonique de la fonction de transfert (pôles et zéros)", a:"$$H(p) = \\dfrac{K}{p^\\alpha}\\cdot\\dfrac{(\\frac{p}{-z_1}+1)(\\frac{p}{-z_2}+1)...}{(\\frac{p}{-p_1}+1)(\\frac{p}{-p_2}+1)...}$$ où les $z_i$ sont les zéros et les $p_i$ les pôles de la fonction de transfert."},
    {id:"formule-ft-premier-ordre", type:"formule", q:"Fonction de transfert caractéristique d'un système du premier ordre", a:"$$H(p) = \\dfrac{S(p)}{E(p)} = \\dfrac{K}{1+\\tau p}$$ $K$ : gain statique, $\\tau$ : constante de temps."},
    {id:"formule-ft-second-ordre", type:"formule", q:"Fonction de transfert caractéristique d'un système du second ordre", a:"$$H(p) = \\dfrac{S(p)}{E(p)} = \\dfrac{K}{1+\\frac{2z}{\\omega_0}p+\\frac{1}{\\omega_0^2}p^2}$$ $K$ : gain statique, $\\omega_0$ : pulsation propre, $z$ : coefficient d'amortissement."},
    {id:"formulaire-laplace-usuelles", type:"formule", q:"Transformées de Laplace usuelles : Dirac, échelon, rampe, exponentielle", a:"Impulsion de Dirac $\\delta(t)$ → $1$<br>Échelon unitaire $u(t)$ → $\\dfrac{1}{p}$<br>Rampe unitaire $t$ → $\\dfrac{1}{p^2}$<br>Exponentielle $e^{-at}$ → $\\dfrac{1}{p+a}$"},
    {id:"def-formalisme-schema-blocs", type:"def", q:"Les 3 éléments du formalisme des schéma-blocs", a:"Les blocs (fonction de transfert d'un sous-système), les points de sommation (addition/soustraction de grandeurs), les points de prélèvement (une grandeur dirigée vers plusieurs blocs)."},
    {id:"methode-blocs-serie-parallele", type:"méthode", q:"Réduction de fonctions de transfert en série et en parallèle", a:"Série : $H(p) = H_1(p)\\times H_2(p)\\times H_3(p)$<br>Parallèle : $H(p) = H_1(p)+H_2(p)$"},
    {id:"methode-deplacement-prelevement", type:"méthode", q:"Règles de déplacement d'un point de prélèvement (aval / amont)", a:"Vers l'aval (après un bloc B) : diviser le bloc de la branche dérivée par B (C devient C/B).<br>Vers l'amont (avant un bloc A) : multiplier le bloc de la branche dérivée par A (C devient A·C)."},
    {id:"methode-deplacement-sommateur", type:"méthode", q:"Règles de déplacement d'un sommateur (aval / amont)", a:"Vers l'aval (après un bloc B) : multiplier le bloc dérivé par B (C devient B·C).<br>Vers l'amont (avant un bloc A) : diviser le bloc dérivé par A (C devient C/A)."},
    {id:"formule-ftbf", type:"formule", q:"Fonction de Transfert en Boucle Fermée (FTBF)", a:"$$H(p) = \\dfrac{S(p)}{E(p)} = \\dfrac{A(p)}{1+A(p)B(p)}$$ avec $A(p)$ la chaîne directe et $B(p)$ la chaîne de retour (de mesure)."},
    {id:"def-ftbo", type:"def", q:"Définition et expression de la Fonction de Transfert en Boucle Ouverte (FTBO)", a:"Fonction de transfert du système pour laquelle le retour sur le sommateur est coupé — comprend la chaîne directe ET la chaîne de mesure.<br>$$FTBO(p) = A(p)\\cdot B(p)$$"},
    {id:"formule-ft-retour-unitaire", type:"formule", q:"Fonction de transfert d'un système à retour unitaire, en fonction de la FTBO", a:"$$H(p) = \\dfrac{S(p)}{E(p)} = \\dfrac{FTBO(p)}{1+FTBO(p)}$$"},
    {id:"formule-systeme-perturbe", type:"formule", q:"Fonction de transfert d'un système perturbé (entrée principale $E(p)$ et perturbation $T(p)$)", a:"$$S(p) = \\dfrac{K(p)G(p)}{1+FTBO}E(p) + \\dfrac{G(p)}{1+FTBO}T(p)$$ Obtenu par superposition des deux schémas ($T=0$ puis $E=0$)."}
  ]
});
